type: "transformation"
version: "1.0"
pipeline:
  components:
    SQL:
      type: "sql"
      parameters:
        componentName: "SQL"
        query: "select Top 20000000 * from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "SQL"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "SCD_PRACTICE_DB"
        schema: "SCD2"
        targetTable: "store_sale2"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    SQL:
      position:
        x: -230
        "y": 20
      tempMetlId: 1
    Rewrite Table:
      position:
        x: -120
        "y": 20
      tempMetlId: 2
