type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Print Variables"
      parameters:
        componentName: "Start"
    Log Started:
      type: "sql-executor"
      transitions:
        success:
        - "Run the SCD  Pipeline"
      parameters:
        componentName: "Log Started"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "INSERT INTO EDW_LAB.STAGE_SCHEMA.LOAD_LOG(LOAD_ID,JOB_NAME,TABLE_NAME,\
          \ SCD_TYPE,STATUS,START_TIME)\r\nVALUES('${sysvar.thisPipeline.executionId}','${jv_job_name}','${jv_table_name}','${jv_scd_type}','Job\
          \ is Started',CURRENT_TIMESTAMP)"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run the SCD  Pipeline:
      type: "run-transformation"
      transitions:
        success:
        - "Log Completed"
        failure:
        - "Print Variables 2"
      parameters:
        componentName: "Run the SCD  Pipeline"
        transformationJob: "Source to Fact/${jv_job_name}"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage: ""
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.childPipeline.vars.v_error_message}"
        - - "jv_updated_rows"
          - "${sysvar.childPipeline.vars.jv_updated_rows}"
        - - "jv_inserted_rows"
          - "${sysvar.childPipeline.vars.jv_inserted_rows}"
    Log Completed:
      type: "sql-executor"
      parameters:
        componentName: "Log Completed"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "update EDW_LAB.STAGE_SCHEMA.LOAD_LOG\r\nSET\r\n    INSERTED_ROWS='${jv_inserted_rows}',\r\
          \n    UPDATED_ROWS='${jv_updated_rows}',\r\n    STATUS='Completed Successfully',\r\
          \n    END_TIME=CURRENT_TIMESTAMP\r\nwhere LOAD_ID='${sysvar.thisPipeline.executionId}'\
          \ and JOB_NAME='${jv_job_name}'\r\n"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Failed:
      type: "sql-executor"
      parameters:
        componentName: "Log Failed"
        scriptLocation: "Component"
        declareSqlVariables: "Include all"
        sqlScript: "update EDW_LAB.STAGE_SCHEMA.LOAD_LOG\r\nSET\r\n    INSERTED_ROWS='${jv_inserted_rows}',\r\
          \n    UPDATED_ROWS='${jv_updated_rows}',\r\n    STATUS='FAILED',\r\n   \
          \ END_TIME=CURRENT_TIMESTAMP,ERROR_MESSAGE='${v_error_message}'\r\nwhere\
          \ LOAD_ID='${sysvar.thisPipeline.executionId}' and JOB_NAME='${jv_job_name}'"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables:
      type: "print-variables"
      transitions:
        success:
        - "Log Started"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "jv_job_name"
        - - "jv_table_name"
        prefixText: "JOB Details= "
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 2:
      type: "print-variables"
      transitions:
        success:
        - "Log Failed"
      parameters:
        componentName: "Print Variables 2"
        variablesToPrint:
        - - "v_error_message"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_row_count:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "-1"
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "-1"
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "-1"
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Failed messages"
    jv_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "t_Stg_Region_to_Dim_Region_Scd1"
    jv_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "ABC"
    jv_scd_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start:
      position:
        x: -1180
        "y": 50
      tempMetlId: 1
    Log Started:
      position:
        x: -890
        "y": 50
      tempMetlId: 2
    Run the SCD  Pipeline:
      position:
        x: -770
        "y": 50
      tempMetlId: 3
    Log Completed:
      position:
        x: -630
        "y": -20
      tempMetlId: 4
    Log Failed:
      position:
        x: -540
        "y": 150
      tempMetlId: 5
    Print Variables:
      position:
        x: -1040
        "y": 50
      tempMetlId: 6
    Print Variables 2:
      position:
        x: -690
        "y": 150
      tempMetlId: 7
