type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Query Result To Grid"
      parameters:
        componentName: "Start"
    Query Result To Grid:
      type: "query-to-grid"
      transitions:
        success:
        - "Grid Iterator"
      parameters:
        componentName: "Query Result To Grid"
        mode: "Advanced"
        gridVariable: "gv_scd2_job_name"
        gridVariableMapping:
        - - "JOB_NAME"
          - "job_name"
        - - "TABLE_NAME"
          - "table_name"
        query: "SELECT JOB_NAME,TABLE_NAME FROM EDW_LAB.STAGE_SCHEMA.JOB_METADATA_TABLE_SCD2\
          \ WHERE ACTIVE_FLAG=TRUE"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Orchestration:
      type: "run-orchestration"
      parameters:
        componentName: "Run Orchestration"
        orchestrationJob: "Source to Fact/Load_SCD.orch.yaml"
        setScalarVariables:
        - - "jv_job_name"
          - "${jv_job_name}"
        - - "jv_table_name"
          - "${jv_table_name}"
        - - "jv_scd_type"
          - "${jv_scd_type}"
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Grid Iterator:
      type: "grid-iterator"
      transitions:
        success:
        - "End Success"
        failure:
        - "End Failure"
      iterationTarget: "Run Orchestration"
      parameters:
        componentName: "Grid Iterator"
        gridVariable: "gv_scd2_job_name"
        gridIteratorVariableMapping:
        - - "job_name"
          - "jv_job_name"
        - - "table_name"
          - "jv_table_name"
        breakOnFailure: "No"
        concurrency: "Sequential"
      postProcessing:
        updateOutputMessage: "${jv_job_name} is Running in this Batch"
        updateScalarVariables:
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_scd_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SCD_Type2"
    gv_scd2_job_name:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          job_name:
            columnType: "TEXT"
          table_name:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -580
        "y": 10
      tempMetlId: 1
    Query Result To Grid:
      position:
        x: -420
        "y": 10
      tempMetlId: 2
    Run Orchestration:
      position:
        x: -260
        "y": -10
      tempMetlId: 3
    Grid Iterator:
      position:
        x: -260
        "y": -10
      tempMetlId: 4
    End Success:
      position:
        x: -100
        "y": 10
      tempMetlId: 5
    End Failure:
      position:
        x: -180
        "y": 160
      tempMetlId: 6
