type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Read Table Metadata "
      parameters:
        componentName: "Start"
    'Read Table Metadata ':
      type: "query-to-grid"
      transitions:
        success:
        - "Log Append 3 2"
      parameters:
        componentName: "Read Table Metadata "
        mode: "Advanced"
        gridVariable: "gv_scd1_job_name"
        gridVariableMapping:
        - - "JOB_NAME"
          - "job_name"
        - - "TABLE_NAME"
          - "table_name"
        query: "SELECT JOB_NAME,TABLE_NAME FROM EDW_LAB.STAGE_SCHEMA.JOB_METADATA_TABLE_SCD1\
          \ WHERE ACTIVE_FLAG=TRUE"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Orchestration:
      type: "run-orchestration"
      parameters:
        componentName: "Run Orchestration"
        orchestrationJob: "Source to Fact/Load_SCD.orch.yaml"
        setScalarVariables:
        - - "jv_job_name"
          - "${jv_job_name}"
        - - "jv_table_name"
          - "${jv_table_name}"
        - - "jv_scd_type"
          - "${jv_scd_type}"
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_error_message"
          - "${sysvar.childPipeline.vars.v_error_message}"
    Grid Iterator:
      type: "grid-iterator"
      transitions:
        success:
        - "Log Append 3 2 2"
        failure:
        - "Append To Grid"
      iterationTarget: "Run Orchestration"
      skipped: false
      parameters:
        componentName: "Grid Iterator"
        gridVariable: "gv_scd1_job_name"
        gridIteratorVariableMapping:
        - - "job_name"
          - "jv_job_name"
        - - "table_name"
          - "jv_table_name"
        concurrency: "Concurrent"
      postProcessing:
        updateOutputMessage: "${jv_job_name} is Running in this Batch"
        updateScalarVariables:
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Append 3 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Print Variables 2"
        - "Grid Iterator"
      skipped: false
      parameters:
        componentName: "Log Append 3 2"
        operation: "Append"
        targetGridVariable: "gv_load_log_scd1"
        valuesGrid:
        - - " ${sysvar.thisComponent.taskId}"
          - "${sysvar.thisPipeline.fullName}"
          - "${sysvar.rootPipeline.executionId}"
          - "${jv_table_name}"
          - "table"
          - "0"
          - "0"
          - "${new Date().toISOString()}"
          - "Y"
          - "${sysvar.thisComponent.startedAt}"
          - ""
          - "0"
          - "0"
          - "Job Started at Main"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 2:
      type: "print-variables"
      parameters:
        componentName: "Print Variables 2"
        variablesToPrint:
        - - "gv_load_log_scd1"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Load Inserted:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "End Success"
      parameters:
        componentName: "Load Inserted"
        pipelineName: "EDW_LAB#load_log_insert_orc"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_load_log"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_load_log_scd1"
              columns:
              - "gv_load_id"
              - "gv_job_name"
              - "gv_job_parent"
              - "gv_table_name"
              - "gv_table_type"
              - "gv_inserted_rows"
              - "gv_updated_rows"
              - "gv_process_date"
              - "gv_success_flag"
              - "gv_start_time"
              - "gv_end_time"
              - "gv_row_count"
              - "gv_status"
              - "gv_message"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Append 3 2 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Load Inserted"
      skipped: false
      parameters:
        componentName: "Log Append 3 2 2"
        operation: "Append"
        targetGridVariable: "gv_load_log_scd1"
        valuesGrid:
        - - " ${sysvar.thisComponent.taskId}"
          - "${sysvar.thisPipeline.fullName}"
          - "${sysvar.rootPipeline.executionId}"
          - "${jv_table_name}"
          - "table"
          - "0"
          - "0"
          - "${new Date().toISOString()}"
          - "Y"
          - ""
          - "${.thisComponent.mainTaskFinishedAt}"
          - "0"
          - "Success"
          - "Main Job is Completed"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Append To Grid:
      type: "append-to-grid"
      transitions:
        success:
        - "End Failure"
      skipped: true
      parameters:
        componentName: "Append To Grid"
        operation: "Append"
        targetGridVariable: "gv_error_log"
        valuesGrid:
        - - "${sysvar.rootPipeline.executionId}"
          - "${jv_job_name}"
          - "${sysvar.thisPipeline.fullName}"
          - "${jv_table_name}"
          - "Dimensions SCD1"
          - "${jv_error_message}"
          - "${new Date().toISOString()}"
          - "${sysvar..thisComponent.mainTaskFinishedAt}"
          - "Failed"
          - "Error occurred execution during "
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_scd_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "SCD_Type1"
    gv_load_log_scd1:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "TEXT"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "NUMBER"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "TEXT"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
      defaultValue: []
    gv_error_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "TEXT"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_error_rows:
            columnType: "TEXT"
          gv_run_date:
            columnType: "TEXT"
          gv_run_time:
            columnType: "TEXT"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
      defaultValue:
      - - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "1970-01-01"
        - "1970-01-01"
        - "-1"
        - "-1"
    gv_scd1_job_name:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          job_name:
            columnType: "TEXT"
          table_name:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -900
        "y": 30
      tempMetlId: 1
    'Read Table Metadata ':
      position:
        x: -730
        "y": 30
      tempMetlId: 2
    Run Orchestration:
      position:
        x: -380
        "y": 10
      tempMetlId: 3
    Grid Iterator:
      position:
        x: -380
        "y": 10
      tempMetlId: 4
    End Success:
      position:
        x: 130
        "y": 30
      tempMetlId: 5
    End Failure:
      position:
        x: -70
        "y": 260
      tempMetlId: 6
    Log Append 3 2:
      position:
        x: -580
        "y": 30
      tempMetlId: 8
    Print Variables 2:
      position:
        x: -510
        "y": -100
      tempMetlId: 9
    Load Inserted:
      position:
        x: -20
        "y": 30
      tempMetlId: 10
    Log Append 3 2 2:
      position:
        x: -200
        "y": 30
      tempMetlId: 11
    Append To Grid:
      position:
        x: -320
        "y": 260
      tempMetlId: 12
