type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "SQL Script"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      parameters:
        componentName: "Run Transformation"
        transformationJob:
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script:
      type: "sql-executor"
      transitions:
        success:
        - "Run Transformation"
      parameters:
        componentName: "SQL Script"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -380
        "y": -10
      tempMetlId: 1
    Run Transformation:
      position:
        x: -120
        "y": -10
      tempMetlId: 2
    SQL Script:
      position:
        x: -260
        "y": -10
      tempMetlId: 3
