type: "transformation"
version: "1.0"
pipeline:
  components:
    JUNK_LINE_FLAG_DIM:
      type: "table-output"
      sources:
      - "Calculator"
      parameters:
        componentName: "JUNK_LINE_FLAG_DIM"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "JUNK_FLAG_DIM"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "m_L_SHIPINSTRUCT"
          - "L_SHIPINSTRUCT"
        - - "m_L_SHIPMODE"
          - "L_SHIPMODE"
        - - "m_L_RETURNFLAG"
          - "L_RETURNFLAG"
        - - "m_L_LINESTATUS"
          - "L_LINESTATUS"
        - - "active_flag"
          - "ACTIVE_FLAG"
        - - "updated_date"
          - "UPDATED_DATE"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Calculator:
      type: "calculator"
      sources:
      - "Join"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "'Y'"
          - "active_flag"
        - - "CURRENT_DATE()"
          - "updated_date"
    Join:
      type: "join"
      sources:
      - "Distinct"
      parameters:
        componentName: "Join"
        mainTable: "Distinct"
        mainTableAlias: "m"
        joins:
        - - "Distinct"
          - "c"
          - "Full"
        joinExpressions:
        - - "\"m\".\"L_RETURNFLAG\"=\"c\".\"L_RETURNFLAG\"AND\"m\".\"L_LINESTATUS\"\
            =\"c\".\"L_LINESTATUS\"AND\"m\".\"L_SHIPINSTRUCT\"=\"c\".\"L_SHIPINSTRUCT\"\
            AND\"c\".\"L_SHIPMODE\"=\"m\".\"L_SHIPMODE\""
          - "m_Full_c"
        columnMappings:
        - - "m.L_RETURNFLAG"
          - "m_L_RETURNFLAG"
        - - "m.L_LINESTATUS"
          - "m_L_LINESTATUS"
        - - "m.L_SHIPINSTRUCT"
          - "m_L_SHIPINSTRUCT"
        - - "m.L_SHIPMODE"
          - "m_L_SHIPMODE"
    LINEITEM:
      type: "table-input"
      parameters:
        componentName: "LINEITEM"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF1"
        targetTable: "LINEITEM"
        columnNames:
        - "L_RETURNFLAG"
        - "L_LINESTATUS"
        - "L_SHIPINSTRUCT"
        - "L_SHIPMODE"
        timeOffset:
    Distinct:
      type: "distinct"
      sources:
      - "LINEITEM"
      parameters:
        componentName: "Distinct"
        columns:
        - "L_RETURNFLAG"
        - "L_LINESTATUS"
        - "L_SHIPINSTRUCT"
        - "L_SHIPMODE"
design:
  components:
    JUNK_LINE_FLAG_DIM:
      position:
        x: 350
        "y": 30
      tempMetlId: 5
    Calculator:
      position:
        x: 140
        "y": 30
      tempMetlId: 6
    Join:
      position:
        x: -30
        "y": 30
      tempMetlId: 8
    LINEITEM:
      position:
        x: -360
        "y": 30
      tempMetlId: 9
    Distinct:
      position:
        x: -200
        "y": 30
      tempMetlId: 10
