type: "transformation"
version: "1.0"
pipeline:
  components:
    STAGE_ORDERS:
      type: "table-input"
      parameters:
        componentName: "STAGE_ORDERS"
        database: "EDW_LAB"
        schema: "STAGE_SCHEMA"
        targetTable: "STAGE_ORDERS"
        columnNames:
        - "O_ORDERKEY"
        - "O_CUSTKEY"
        - "O_ORDERSTATUS"
        - "O_TOTALPRICE"
        - "O_ORDERDATE"
        - "O_ORDERPRIORITY"
        - "O_CLERK"
        - "O_SHIPPRIORITY"
        - "O_COMMENT"
        - "LOAD_DATE"
        timeOffset:
    DIM_CUSTOMER_SCD2:
      type: "table-input"
      parameters:
        componentName: "DIM_CUSTOMER_SCD2"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_CUSTOMER_SCD2"
        columnNames:
        - "C_SRGKEY"
        - "C_CUSTKEY"
        - "C_ACTIVE_FLAG"
        timeOffset:
    Active Customers:
      type: "join"
      sources:
      - "STAGE_ORDERS"
      - "DIM_CUSTOMER_SCD2"
      parameters:
        componentName: "Active Customers"
        mainTable: "STAGE_ORDERS"
        mainTableAlias: "ORDER"
        joins:
        - - "DIM_CUSTOMER_SCD2"
          - "CUST"
          - "Inner"
        joinExpressions:
        - - "\"ORDER\".\"O_CUSTKEY\"=\"CUST\".\"C_CUSTKEY\" and \"CUST\".\"C_ACTIVE_FLAG\"\
            ='Y'"
          - "ORDER_Inner_CUST"
        columnMappings:
        - - "ORDER.O_ORDERKEY"
          - "V_ORDER.O_ORDERKEY"
        - - "CUST.C_SRGKEY"
          - "V_CUST.C_SRGKEY"
        - - "ORDER.O_ORDERSTATUS"
          - "ORDER.O_ORDERSTATUS"
        - - "ORDER.O_TOTALPRICE"
          - "ORDER.O_TOTALPRICE"
        - - "ORDER.O_ORDERDATE"
          - "ORDER.O_ORDERDATE"
        - - "ORDER.O_ORDERPRIORITY"
          - "ORDER.O_ORDERPRIORITY"
        - - "ORDER.O_CLERK"
          - "ORDER.O_CLERK"
        - - "ORDER.O_SHIPPRIORITY"
          - "ORDER.O_SHIPPRIORITY"
        - - "ORDER.O_COMMENT"
          - "ORDER.O_COMMENT"
        - - "ORDER.LOAD_DATE"
          - "ORDER.LOAD_DATE"
    'Date check ':
      type: "join"
      sources:
      - "Active Customers"
      - "DATE_DIMENSION"
      parameters:
        componentName: "Date check "
        mainTable: "Active Customers"
        mainTableAlias: "cust_ord"
        joins:
        - - "DATE_DIMENSION"
          - "dd"
          - "Inner"
        joinExpressions:
        - - "\"cust_ord\".\"ORDER.O_ORDERDATE\"=\"dd\".\"DATE\""
          - "cust_ord_Inner_dd"
        columnMappings:
        - - "dd.DATE"
          - "DATE"
        - - "cust_ord.V_ORDER.O_ORDERKEY"
          - "V_ORDER.O_ORDERKEY"
        - - "cust_ord.V_CUST.C_SRGKEY"
          - "V_CUST.C_SRGKEY"
        - - "cust_ord.ORDER.O_ORDERSTATUS"
          - "ORDER.O_ORDERSTATUS"
        - - "cust_ord.ORDER.O_TOTALPRICE"
          - "ORDER.O_TOTALPRICE"
        - - "cust_ord.ORDER.O_ORDERDATE"
          - "ORDER.O_ORDERDATE"
        - - "cust_ord.ORDER.O_ORDERPRIORITY"
          - "ORDER.O_ORDERPRIORITY"
        - - "cust_ord.ORDER.O_CLERK"
          - "ORDER.O_CLERK"
        - - "cust_ord.ORDER.O_SHIPPRIORITY"
          - "ORDER.O_SHIPPRIORITY"
        - - "cust_ord.ORDER.O_COMMENT"
          - "ORDER.O_COMMENT"
        - - "cust_ord.ORDER.LOAD_DATE"
          - "ORDER.LOAD_DATE"
    DATE_DIMENSION:
      type: "table-input"
      parameters:
        componentName: "DATE_DIMENSION"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DATE_DIMENSION"
        columnNames:
        - "DATE"
        timeOffset:
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Date check "
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "ACTIVE ORDERS"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    STAGE_ORDERS:
      position:
        x: -220
        "y": -10
      tempMetlId: 1
    DIM_CUSTOMER_SCD2:
      position:
        x: -210
        "y": 80
      tempMetlId: 4
    Active Customers:
      position:
        x: 30
        "y": 40
      tempMetlId: 5
    'Date check ':
      position:
        x: 230
        "y": 80
      tempMetlId: 6
    DATE_DIMENSION:
      position:
        x: -210
        "y": 180
      tempMetlId: 7
    Rewrite Table:
      position:
        x: 390
        "y": 80
      tempMetlId: 8
