type: "transformation"
version: "1.0"
pipeline:
  components:
    STG_PART_SCD1:
      type: "table-input"
      parameters:
        componentName: "STG_PART_SCD1"
        database: "EDW_LAB"
        schema: "STAGE_SCHEMA"
        targetTable: "STAGE_PART_SCD1"
        columnNames:
        - "P_PARTKEY"
        - "P_NAME"
        - "P_MFGR"
        - "P_BRAND"
        - "P_TYPE"
        - "P_SIZE"
        - "P_CONTAINER"
        - "P_RETAILPRICE"
        - "P_COMMENT"
        - "START_TIME"
        timeOffset:
    DIM_PART_SCD1:
      type: "table-update"
      sources:
      - "Updated date"
      parameters:
        componentName: "DIM_PART_SCD1"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_PART_SCD1"
        targetAlias: "target"
        sourceAlias: "source"
        joinExpression:
        - - "\"source\".\"P_PARTKEY\"=\"target\".\"P_PARTKEY\""
          - "Case"
        whenMatched:
        - - "\"source\".\"P_PARTKEY\"=\"target\".\"P_PARTKEY\""
          - "Update"
        updateMapping:
        - - "P_PARTKEY"
          - "P_PARTKEY"
        - - "P_NAME"
          - "P_NAME"
        - - "P_MFGR"
          - "P_MFGR"
        - - "P_BRAND"
          - "P_BRAND"
        - - "P_TYPE"
          - "P_TYPE"
        - - "P_SIZE"
          - "P_SIZE"
        - - "P_CONTAINER"
          - "P_CONTAINER"
        - - "P_RETAILPRICE"
          - "P_RETAILPRICE"
        - - "P_COMMENT"
          - "P_COMMENT"
        - - "START_TIME"
          - "P_LOAD_TIME"
        - - "v_updated"
          - "P_UPDATE_AT"
        includeNotMatched: "Yes"
        insertMapping:
        - - "P_PARTKEY"
          - "P_PARTKEY"
        - - "P_NAME"
          - "P_NAME"
        - - "P_MFGR"
          - "P_MFGR"
        - - "P_BRAND"
          - "P_BRAND"
        - - "P_TYPE"
          - "P_TYPE"
        - - "P_SIZE"
          - "P_SIZE"
        - - "P_CONTAINER"
          - "P_CONTAINER"
        - - "P_RETAILPRICE"
          - "P_RETAILPRICE"
        - - "P_COMMENT"
          - "P_COMMENT"
        - - "START_TIME"
          - "P_LOAD_TIME"
        - - "v_updated"
          - "P_UPDATE_AT"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_inserted_rows"
          - "${sysvar.thisComponent.rowsInserted}"
        - - "jv_updated_rows"
          - "${sysvar.thisComponent.rowsUpdated}"
    Find Unique:
      type: "rank"
      sources:
      - "STG_PART_SCD1"
      parameters:
        componentName: "Find Unique"
        includeInputColumns: "Yes"
        partitionData:
        - "P_PARTKEY"
        - "P_NAME"
        - "P_MFGR"
        - "P_BRAND"
        - "P_TYPE"
        - "P_SIZE"
        - "P_CONTAINER"
        - "P_RETAILPRICE"
        - "P_COMMENT"
        orderingWithinPartitions:
        - - "P_PARTKEY"
          - "Ascending"
        - - "START_TIME"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    PART:
      type: "filter"
      sources:
      - "Find Unique"
      parameters:
        componentName: "PART"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    Updated date:
      type: "calculator"
      sources:
      - "PART"
      parameters:
        componentName: "Updated date"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "v_updated"
  variables:
    jv_src_schema:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    JV_Source_object_id_NEW:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_tar_db:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_tar_scheam:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_source_object_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_target_table:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_src_db:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    STG_PART_SCD1:
      position:
        x: -1190
        "y": -80
      tempMetlId: 1
    DIM_PART_SCD1:
      position:
        x: -550
        "y": -80
      tempMetlId: 2
    Find Unique:
      position:
        x: -1040
        "y": -80
      tempMetlId: 3
    PART:
      position:
        x: -900
        "y": -80
      tempMetlId: 4
    Updated date:
      position:
        x: -740
        "y": -80
      tempMetlId: 5
