type: "transformation"
version: "1.0"
pipeline:
  components:
    STAGE_NATION:
      type: "table-input"
      parameters:
        componentName: "STAGE_NATION"
        database: "EDW_LAB"
        schema: "STAGE_SCHEMA"
        targetTable: "STAGE_NATION"
        columnNames:
        - "N_NATIONKEY"
        - "N_NAME"
        - "N_REGIONKEY"
        - "N_COMMENT"
        - "N_START_TIME"
        timeOffset:
    Load Date:
      type: "calculator"
      sources:
      - "Filter"
      parameters:
        componentName: "Load Date"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_DATE()"
          - "v_load_date"
    DIM_NATION:
      type: "table-output"
      sources:
      - "Load Date"
      parameters:
        componentName: "DIM_NATION"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_NATION"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "N_NATIONKEY"
          - "N_NATIONKEY"
        - - "N_NAME"
          - "N_NAME"
        - - "N_REGIONKEY"
          - "N_REGIONKEY"
        - - "N_COMMENT"
          - "N_COMMENT"
        - - "v_load_date"
          - "N_LOAD_DATE"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_updated_rows"
          - "${sysvar.thisComponent.rowCount}"
    Rank:
      type: "rank"
      sources:
      - "STAGE_NATION"
      parameters:
        componentName: "Rank"
        includeInputColumns: "Yes"
        partitionData:
        - "N_NATIONKEY"
        - "N_NAME"
        - "N_REGIONKEY"
        - "N_COMMENT"
        orderingWithinPartitions:
        - - "N_NATIONKEY"
          - "Ascending"
        - - "N_START_TIME"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    Filter:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
  variables:
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    STAGE_NATION:
      position:
        x: -620
        "y": -40
      tempMetlId: 1
    Load Date:
      position:
        x: -160
        "y": -40
      tempMetlId: 3
    DIM_NATION:
      position:
        x: -10
        "y": -40
      tempMetlId: 4
    Rank:
      position:
        x: -480
        "y": -40
      tempMetlId: 8
    Filter:
      position:
        x: -360
        "y": -40
      tempMetlId: 9
