type: "transformation"
version: "1.0"
pipeline:
  components:
    RAW_USER_DETAILS:
      type: "table-input"
      parameters:
        componentName: "RAW_USER_DETAILS"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "USERS_DATA_API"
        columnNames:
        - "DATA_VALUE"
        timeOffset:
    Extract Nested Data 3:
      type: "extract-nested-data-sf"
      sources:
      - "RAW_USER_DETAILS"
      parameters:
        componentName: "Extract Nested Data 3"
        includeInputColumns: "Yes"
        columns:
        - name: "website"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "website"
          isArray: "false"
          include: "true"
        - name: "address"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "address"
          isArray: "false"
          include: "true"
          childElements:
          - name: "geo"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "geo"
            isArray: "false"
            include: "true"
            childElements:
            - name: "lat"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "lat"
              isArray: "false"
              include: "true"
            - name: "lng"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "lng"
              isArray: "false"
              include: "true"
          - name: "city"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "city"
            isArray: "false"
            include: "true"
          - name: "suite"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "suite"
            isArray: "false"
            include: "true"
          - name: "zipcode"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "zipcode"
            isArray: "false"
            include: "true"
          - name: "street"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "street"
            isArray: "false"
            include: "true"
        - name: "phone"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "phone"
          isArray: "false"
          include: "true"
        - name: "name"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "name"
          isArray: "false"
          include: "true"
        - name: "company"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "company"
          isArray: "false"
          include: "true"
          childElements:
          - name: "catchPhrase"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "catchPhrase"
            isArray: "false"
            include: "true"
          - name: "bs"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "bs"
            isArray: "false"
            include: "true"
          - name: "name"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "company_name"
            isArray: "false"
            include: "true"
        - name: "id"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "id"
          isArray: "false"
          include: "true"
        - name: "email"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "email"
          isArray: "false"
          include: "true"
        - name: "username"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "username"
          isArray: "false"
          include: "true"
        outerJoin: "Yes"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    STG_USER_DETAILS:
      type: "table-output"
      sources:
      - "LOAD TIME INSERT"
      parameters:
        componentName: "STG_USER_DETAILS"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STG_USER_DETAILS"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "website"
          - "WEBSITE"
        - - "id"
          - "EMP_ID"
        - - "name"
          - "EMP_NAME"
        - - "username"
          - "USER_NAME"
        - - "company_name"
          - "COMPANY_NAME"
        - - "email"
          - "EMAIL"
        - - "phone"
          - "PHONE_NUMBER"
        - - "city"
          - "CITY"
        - - "bs"
          - "BS"
        - - "catchPhrase"
          - "CATCHPHRASE"
        - - "street"
          - "STREET"
        - - "zipcode"
          - "ZIPCODE"
        - - "suite"
          - "SUITE"
        - - "lat"
          - "LATITUDE"
        - - "lng"
          - "LONGITUDE"
        - - "LOAD_TIME_V"
          - "LOAD_TIME"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    LOAD TIME INSERT:
      type: "calculator"
      sources:
      - "Extract Nested Data 3"
      parameters:
        componentName: "LOAD TIME INSERT"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "LOAD_TIME_V"
design:
  components:
    RAW_USER_DETAILS:
      position:
        x: -1650
        "y": -180
      tempMetlId: 2
    Extract Nested Data 3:
      position:
        x: -1470
        "y": -180
      tempMetlId: 6
    STG_USER_DETAILS:
      position:
        x: -1140
        "y": -180
      tempMetlId: 13
    LOAD TIME INSERT:
      position:
        x: -1310
        "y": -180
      tempMetlId: 14
