type: "transformation"
version: "1.0"
pipeline:
  components:
    STG_USER_DETAILS:
      type: "table-input"
      parameters:
        componentName: "STG_USER_DETAILS"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STG_USER_DETAILS"
        columnNames:
        - "WEBSITE"
        - "EMP_ID"
        - "EMP_NAME"
        - "USER_NAME"
        - "COMPANY_NAME"
        - "EMAIL"
        - "PHONE_NUMBER"
        - "CITY"
        - "BS"
        - "CATCHPHRASE"
        - "STREET"
        - "ZIPCODE"
        - "SUITE"
        - "LATITUDE"
        - "LONGITUDE"
        - "LOAD_TIME"
        timeOffset:
    DIM_USER_DETAILS_SCD2:
      type: "table-input"
      parameters:
        componentName: "DIM_USER_DETAILS_SCD2"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "DIM_USER_DETAILS_SCD2"
        columnNames:
        - "WEBSITE"
        - "EMP_ID"
        - "EMP_NAME"
        - "USER_NAME"
        - "COMPANY_NAME"
        - "EMAIL"
        - "PHONE_NUMBER"
        - "CITY"
        - "BS"
        - "CATCHPHRASE"
        - "STREET"
        - "ZIPCODE"
        - "SUITE"
        - "LATITUDE"
        - "LONGITUDE"
        - "LOAD_TIME"
        - "END_TIME"
        timeOffset:
    CURRENT DATA:
      type: "sql"
      sources:
      - "DIM_USER_DETAILS_SCD2"
      parameters:
        componentName: "CURRENT DATA"
        query: "SELECT * FROM EDW_LAB.PUBLIC.DIM_USER_DETAILS_SCD2 WHERE END_TIME\
          \ IS NULL"
    Rank:
      type: "rank"
      sources:
      - "STG_USER_DETAILS"
      parameters:
        componentName: "Rank"
        includeInputColumns: "Yes"
        partitionData:
        - "WEBSITE"
        - "EMP_ID"
        - "EMP_NAME"
        - "USER_NAME"
        - "COMPANY_NAME"
        - "EMAIL"
        - "PHONE_NUMBER"
        - "CITY"
        - "BS"
        - "CATCHPHRASE"
        - "STREET"
        - "ZIPCODE"
        - "SUITE"
        - "LATITUDE"
        - "LONGITUDE"
        orderingWithinPartitions:
        - - "LOAD_TIME"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    Detect Changes:
      type: "detect-changes"
      sources:
      - "CURRENT DATA"
      - "Filter"
      parameters:
        componentName: "Detect Changes"
        masterTable: "CURRENT DATA"
        matchKeys:
        - "WEBSITE"
        - "EMP_ID"
        - "EMP_NAME"
        - "USER_NAME"
        - "COMPANY_NAME"
        - "EMAIL"
        - "PHONE_NUMBER"
        - "CITY"
        - "BS"
        - "CATCHPHRASE"
        - "STREET"
        - "ZIPCODE"
        - "SUITE"
        - "LATITUDE"
        - "LONGITUDE"
        compareColumns:
        - "EMP_ID"
        - "WEBSITE"
        - "EMP_NAME"
        - "USER_NAME"
        - "COMPANY_NAME"
        - "EMAIL"
        - "PHONE_NUMBER"
        - "CITY"
        - "BS"
        - "CATCHPHRASE"
        - "STREET"
        - "ZIPCODE"
        - "SUITE"
        - "LATITUDE"
        - "LONGITUDE"
        outputColumnMapping:
        - - "compare_EMP_ID"
          - "compare_EMP_ID"
        - - "compare_WEBSITE"
          - "compare_WEBSITE"
        - - "compare_EMP_NAME"
          - "compare_EMP_NAME"
        - - "compare_USER_NAME"
          - "compare_USER_NAME"
        - - "compare_COMPANY_NAME"
          - "compare_COMPANY_NAME"
        - - "compare_EMAIL"
          - "compare_EMAIL"
        - - "compare_PHONE_NUMBER"
          - "compare_PHONE_NUMBER"
        - - "compare_CITY"
          - "compare_CITY"
        - - "compare_BS"
          - "compare_BS"
        - - "compare_CATCHPHRASE"
          - "compare_CATCHPHRASE"
        - - "compare_STREET"
          - "compare_STREET"
        - - "compare_ZIPCODE"
          - "compare_ZIPCODE"
        - - "compare_SUITE"
          - "compare_SUITE"
        - - "compare_LATITUDE"
          - "compare_LATITUDE"
        - - "compare_LONGITUDE"
          - "compare_LONGITUDE"
        indicatorColumn: "Indicator"
    Filter:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    New data:
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "New data"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "N"
        combineCondition: "And"
    UPDATE DATA:
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "UPDATE DATA"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "C"
        combineCondition: "And"
    Unite:
      type: "unite"
      sources:
      - "CURRENT DATA"
      - "UPDATE DATA"
      parameters:
        componentName: "Unite"
        method: "All Columns"
        castTypes: "Yes"
        addSourceComponentColumn: "No"
        removeDuplicates: "No"
    Rank 2:
      type: "rank"
      sources:
      - "Unite"
      parameters:
        componentName: "Rank 2"
        includeInputColumns: "Yes"
        partitionData:
        - "EMP_ID"
        orderingWithinPartitions:
        - - "LOAD_TIME"
          - "Descending"
        functions:
        - - "Row Number"
          - "RN"
    Filter 2:
      type: "filter"
      sources:
      - "Rank 2"
      parameters:
        componentName: "Filter 2"
        filterConditions:
        - - "RN"
          - "Is"
          - "Greater than"
          - "1"
        combineCondition: "And"
    Calculator 3:
      type: "calculator"
      sources:
      - "Filter 2"
      parameters:
        componentName: "Calculator 3"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "OLD_END_DATE"
    Calculator:
      type: "calculator"
      sources:
      - "New data"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "V_LOAD_TIME"
        - - "NULL"
          - "V_END_DATE"
    DIM_USER_DETAILS_SCD2 2:
      type: "table-output"
      sources:
      - "Calculator"
      parameters:
        componentName: "DIM_USER_DETAILS_SCD2 2"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "DIM_USER_DETAILS_SCD2"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "compare_WEBSITE"
          - "WEBSITE"
        - - "compare_EMP_ID"
          - "EMP_ID"
        - - "compare_EMP_NAME"
          - "EMP_NAME"
        - - "compare_USER_NAME"
          - "USER_NAME"
        - - "compare_COMPANY_NAME"
          - "COMPANY_NAME"
        - - "compare_EMAIL"
          - "EMAIL"
        - - "compare_PHONE_NUMBER"
          - "PHONE_NUMBER"
        - - "compare_CITY"
          - "CITY"
        - - "compare_BS"
          - "BS"
        - - "compare_CATCHPHRASE"
          - "CATCHPHRASE"
        - - "compare_STREET"
          - "STREET"
        - - "compare_ZIPCODE"
          - "ZIPCODE"
        - - "compare_SUITE"
          - "SUITE"
        - - "compare_LATITUDE"
          - "LATITUDE"
        - - "compare_LONGITUDE"
          - "LONGITUDE"
        - - "V_LOAD_TIME"
          - "LOAD_TIME"
        - - "V_END_DATE"
          - "END_TIME"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Calculator 2:
      type: "calculator"
      sources:
      - "UPDATE DATA"
      parameters:
        componentName: "Calculator 2"
        includeInputColumns: "Yes"
        calculations:
        - - "NULL"
          - "V_END_DATE_UP"
        - - "CURRENT_TIMESTAMP()"
          - "LOAD_TIME_V"
    DIM_USER_DETAILS_SCD2 3:
      type: "table-output"
      sources:
      - "Calculator 2"
      parameters:
        componentName: "DIM_USER_DETAILS_SCD2 3"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "DIM_USER_DETAILS_SCD2"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "compare_WEBSITE"
          - "WEBSITE"
        - - "compare_EMP_ID"
          - "EMP_ID"
        - - "compare_EMP_NAME"
          - "EMP_NAME"
        - - "compare_USER_NAME"
          - "USER_NAME"
        - - "compare_COMPANY_NAME"
          - "COMPANY_NAME"
        - - "compare_EMAIL"
          - "EMAIL"
        - - "compare_PHONE_NUMBER"
          - "PHONE_NUMBER"
        - - "compare_CITY"
          - "CITY"
        - - "compare_BS"
          - "BS"
        - - "compare_CATCHPHRASE"
          - "CATCHPHRASE"
        - - "compare_STREET"
          - "STREET"
        - - "compare_ZIPCODE"
          - "ZIPCODE"
        - - "compare_SUITE"
          - "SUITE"
        - - "compare_LATITUDE"
          - "LATITUDE"
        - - "compare_LONGITUDE"
          - "LONGITUDE"
        - - "LOAD_TIME_V"
          - "LOAD_TIME"
        - - "V_END_DATE_UP"
          - "END_TIME"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    DIM_USER_DETAILS_SCD2 4:
      type: "table-update"
      sources:
      - "Calculator 3"
      parameters:
        componentName: "DIM_USER_DETAILS_SCD2 4"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "DIM_USER_DETAILS_SCD2"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"input\".\"EMP_ID\"=\"target\".\"EMP_ID\"AND\"input\".\"END_TIME\" IS\
            \ NULL AND\"input\".\"LOAD_TIME\"=\"target\".\"LOAD_TIME\""
          - "Case"
        whenMatched:
        - - "\"input\".\"EMP_ID\"=\"target\".\"EMP_ID\"AND\"input\".\"END_TIME\" IS\
            \ NULL AND\"input\".\"LOAD_TIME\"=\"target\".\"LOAD_TIME\""
          - "Update"
        updateMapping:
        - - "OLD_END_DATE"
          - "END_TIME"
        includeNotMatched: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    STG_USER_DETAILS:
      position:
        x: -460
        "y": -40
      tempMetlId: 1
    DIM_USER_DETAILS_SCD2:
      position:
        x: -470
        "y": 100
      tempMetlId: 2
    CURRENT DATA:
      position:
        x: -290
        "y": 100
      tempMetlId: 3
    Rank:
      position:
        x: -340
        "y": -40
      tempMetlId: 4
    Detect Changes:
      position:
        x: -120
        "y": 70
      tempMetlId: 5
    Filter:
      position:
        x: -210
        "y": -40
      tempMetlId: 6
    New data:
      position:
        x: 50
        "y": -40
      tempMetlId: 7
    UPDATE DATA:
      position:
        x: 70
        "y": 80
      tempMetlId: 8
    Unite:
      position:
        x: 100
        "y": 230
      tempMetlId: 13
    Rank 2:
      position:
        x: 210
        "y": 230
      tempMetlId: 14
    Filter 2:
      position:
        x: 320
        "y": 230
      tempMetlId: 15
    Calculator 3:
      position:
        x: 430
        "y": 230
      tempMetlId: 17
    Calculator:
      position:
        x: 240
        "y": -40
      tempMetlId: 20
    DIM_USER_DETAILS_SCD2 2:
      position:
        x: 400
        "y": -40
      tempMetlId: 21
    Calculator 2:
      position:
        x: 230
        "y": 90
      tempMetlId: 22
    DIM_USER_DETAILS_SCD2 3:
      position:
        x: 390
        "y": 90
      tempMetlId: 23
    DIM_USER_DETAILS_SCD2 4:
      position:
        x: 550
        "y": 230
      tempMetlId: 24
