type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "error_log_insert_trans1.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Run Transformation:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
