type: "transformation"
version: "1.0"
pipeline:
  components:
    STG_CUSTOMER_SCD1:
      type: "table-input"
      parameters:
        componentName: "STG_CUSTOMER_SCD1"
        database: "EDW_LAB"
        schema: "STAGE_SCHEMA"
        targetTable: "STAGE_CUSTOMER_SCD1"
        columnNames:
        - "C_CUSTKEY"
        - "C_NAME"
        - "C_ADDRESS"
        - "C_NATIONKEY"
        - "C_PHONE"
        - "C_ACCTBAL"
        - "C_MKTSEGMENT"
        - "C_COMMENT"
        - "START_TIME"
        timeOffset:
    DIM_CUSTOMER_SCD1:
      type: "table-update"
      sources:
      - "Updated date"
      parameters:
        componentName: "DIM_CUSTOMER_SCD1"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_CUSTOMER_SCD1"
        targetAlias: "target"
        sourceAlias: "source"
        joinExpression:
        - - "\"target\".\"C_CUSTKEY\"=\"source\".\"C_CUSTKEY\""
          - "Case"
        whenMatched:
        - - "\"target\".\"C_CUSTKEY\"=\"source\".\"C_CUSTKEY\""
          - "Update"
        updateMapping:
        - - "C_CUSTKEY"
          - "C_CUSTKEY"
        - - "C_NAME"
          - "C_NAME"
        - - "C_ADDRESS"
          - "C_ADDRESS"
        - - "C_NATIONKEY"
          - "C_NATIONKEY"
        - - "C_PHONE"
          - "C_PHONE"
        - - "C_ACCTBAL"
          - "C_ACCTBAL"
        - - "C_MKTSEGMENT"
          - "C_MKTSEGMENT"
        - - "C_COMMENT"
          - "C_COMMENT"
        - - "START_TIME"
          - "C_LOAD_TIME"
        - - "v_updated"
          - "C_UPDATE_AT"
        includeNotMatched: "Yes"
        insertMapping:
        - - "C_CUSTKEY"
          - "C_CUSTKEY"
        - - "C_NAME"
          - "C_NAME"
        - - "C_ADDRESS"
          - "C_ADDRESS"
        - - "C_NATIONKEY"
          - "C_NATIONKEY"
        - - "C_PHONE"
          - "C_PHONE"
        - - "C_ACCTBAL"
          - "C_ACCTBAL"
        - - "C_MKTSEGMENT"
          - "C_MKTSEGMENT"
        - - "C_COMMENT"
          - "C_COMMENT"
        - - "START_TIME"
          - "C_LOAD_TIME"
        - - "v_updated"
          - "C_UPDATE_AT"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_inserted_rows"
          - "${sysvar.thisComponent.rowsInserted}"
        - - "jv_updated_rows"
          - "${sysvar.thisComponent.rowsUpdated}"
    Find Unique:
      type: "rank"
      sources:
      - "STG_CUSTOMER_SCD1"
      parameters:
        componentName: "Find Unique"
        includeInputColumns: "Yes"
        partitionData:
        - "C_CUSTKEY"
        - "C_NAME"
        - "C_ADDRESS"
        - "C_NATIONKEY"
        - "C_PHONE"
        - "C_ACCTBAL"
        - "C_MKTSEGMENT"
        - "C_COMMENT"
        orderingWithinPartitions:
        - - "C_CUSTKEY"
          - "Ascending"
        - - "START_TIME"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    Customer:
      type: "filter"
      sources:
      - "Find Unique"
      parameters:
        componentName: "Customer"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    Updated date:
      type: "calculator"
      sources:
      - "Customer"
      parameters:
        componentName: "Updated date"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "v_updated"
  variables:
    jv_src_schema:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    JV_Source_object_id_NEW:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_tar_db:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_tar_scheam:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_source_object_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_target_table:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_src_db:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    STG_CUSTOMER_SCD1:
      position:
        x: -1170
        "y": -100
      tempMetlId: 1
    DIM_CUSTOMER_SCD1:
      position:
        x: -440
        "y": -80
      tempMetlId: 2
    Find Unique:
      position:
        x: -1040
        "y": -100
      tempMetlId: 3
    Customer:
      position:
        x: -920
        "y": -100
      tempMetlId: 4
    Updated date:
      position:
        x: -680
        "y": -90
      tempMetlId: 5
