# This file contains shared pipelines configuration which defines how they appear to consuming users.
# The configuration is automatically updated when changes are made to shared pipelines in the Designer UI.
# Please exercise caution when manually editing to avoid conflicts or data loss.
# For more information please see our documentation.

version: "1.0"
type: shared-pipelines-config
pipelines:
  - pipeline: SCD_TYPE2_DETECTCHANGES.tran.yaml
    displayName: SCD_TYPE2_DETECTCHANGES
    id: SCD_TYPE2_DETECTCHANGES
    enabled: true
    parameters: {}
  - pipeline: API FLATTEN.tran.yaml
    displayName: API FLATTEN
    id: API-FLATTEN
    enabled: true
    parameters: {}
  - pipeline: Load_Log_share.tran.yaml
    displayName: Load_Log_share
    id: Load_Log
    enabled: true
    parameters: {}
