type: "transformation"
version: "1.0"
pipeline:
  components:
    grid_var_load_log:
      type: "fixed-flow"
      parameters:
        componentName: "grid_var_load_log"
        columns:
        - - "gv_load_id"
          - "NUMBER"
          - ""
          - ""
        - - "gv_job_name"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_job_parent"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_table_name"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_table_type"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_inserted_rows"
          - "NUMBER"
          - ""
          - ""
        - - "gv_updated_rows"
          - "NUMBER"
          - ""
          - ""
        - - "gv_subject_area"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_process_date"
          - "DATE"
          - ""
          - ""
        - - "gv_success_flag"
          - "NUMBER"
          - ""
          - ""
        - - "gv_start_time"
          - "TIMESTAMP"
          - ""
          - ""
        - - "gv_end_time"
          - "TIMESTAMP"
          - ""
          - ""
        - - "gv_row_count"
          - "NUMBER"
          - ""
          - ""
        - - "gv_run_history_id"
          - "NUMBER"
          - ""
          - ""
        - - "gv_status"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_message"
          - "VARCHAR"
          - ""
          - ""
        - - "gv_comment"
          - "VARCHAR"
          - ""
          - ""
        values:
          fromGrid:
            variable: "gv_load_log"
            columns:
            - "gv_load_id"
            - "gv_job_name"
            - "gv_job_parent"
            - "gv_table_name"
            - "gv_table_type"
            - "gv_inserted_rows"
            - "gv_updated_rows"
            - "gv_subject_area"
            - "gv_process_date"
            - "gv_success_flag"
            - "gv_start_time"
            - "gv_end_time"
            - "gv_row_count"
            - "gv_run_history_id"
            - "gv_status"
            - "gv_message"
            - "gv_comment"
    Load log insert:
      type: "table-output"
      sources:
      - "grid_var_load_log"
      parameters:
        componentName: "Load log insert"
        warehouse: "[Environment Default]"
        database: "${ev_sf_database}"
        schema: "${ev_edp_curated_schema}"
        targetTable: "${ev_load_log}"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "gv_load_id"
          - "LOAD_ID"
        - - "gv_job_name"
          - "PROCEDURE_NAME"
        - - "gv_job_parent"
          - "PROCEDURE_PARENT"
        - - "gv_table_name"
          - "TABLE_NAME"
        - - "gv_table_type"
          - "TABLE_TYPE"
        - - "gv_subject_area"
          - "SUBJECT_AREA"
        - - "gv_inserted_rows"
          - "INSERTED_ROWS"
        - - "gv_updated_rows"
          - "UPDATED_ROWS"
        - - "gv_process_date"
          - "PROCESS_DATE"
        - - "gv_success_flag"
          - "SUCCESS_FLAG"
        - - "gv_start_time"
          - "START_TIME"
        - - "gv_end_time"
          - "END_TIME"
        - - "gv_comment"
          - "COMMENTS"
        orderBy:
        outputMode: "Append"
  variables:
    gv_load_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "NUMBER"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "NUMBER"
          gv_subject_area:
            columnType: "TEXT"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "NUMBER"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_run_history_id:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
          gv_comment:
            columnType: "TEXT"
      defaultValue:
      - - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "1970-01-01"
        - "-1"
        - "1970-01-01"
        - "1970-01-01"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
design:
  components:
    grid_var_load_log:
      position:
        x: 160
        "y": 112
      tempMetlId: 4207
    Load log insert:
      position:
        x: 336
        "y": 112
      tempMetlId: 4208
