type: "transformation"
version: "1.0"
pipeline:
  components:
    LINE ITEM:
      type: "table-input"
      parameters:
        componentName: "LINE ITEM"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF1"
        targetTable: "LINEITEM"
        columnNames:
        - "L_ORDERKEY"
        - "L_PARTKEY"
        - "L_SUPPKEY"
        - "L_LINENUMBER"
        - "L_QUANTITY"
        - "L_EXTENDEDPRICE"
        - "L_DISCOUNT"
        - "L_TAX"
        - "L_RETURNFLAG"
        - "L_LINESTATUS"
        - "L_SHIPDATE"
        - "L_COMMITDATE"
        - "L_RECEIPTDATE"
        - "L_SHIPINSTRUCT"
        - "L_SHIPMODE"
        - "L_COMMENT"
        timeOffset:
    LINE ITEM3:
      type: "rewrite-table"
      sources:
      - "LINE ITEM"
      parameters:
        componentName: "LINE ITEM3"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "${v_current_table_name}"
        orderBy:
      postProcessing:
        updateOutputMessage: "JOB 3: LINEITEM TABLE EXECEUTED"
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "STAGE_REGION_TABLE"
design:
  components:
    LINE ITEM:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    LINE ITEM3:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
