type: "transformation"
version: "1.0"
pipeline:
  components:
    'Final Pipeline Status ':
      type: "sql"
      parameters:
        componentName: "Final Pipeline Status "
        query: "SELECT \r\n    CASE \r\n        WHEN COUNT_IF(status = 'FAILED') >\
          \ 0 THEN 'FAILED' \r\n        WHEN COUNT_IF(status = 'PENDING' OR status\
          \ = 'RUNNING') > 0 THEN 'STALLED_OR_INCOMPLETE' -- Should not happen if\
          \ loop condition is correct \r\n        ELSE 'COMPLETED' \r\n    END AS\
          \ PIPELINE_FINAL_STATUS \r\nFROM edw_lab.public.job_status\r\n \r\n"
  variables:
    v_pipeline_status:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    'Final Pipeline Status ':
      position:
        x: -230
        "y": -30
      tempMetlId: 1
