type: "transformation"
version: "1.0"
pipeline:
  components:
    DIM_ORDERS:
      type: "table-input"
      parameters:
        componentName: "DIM_ORDERS"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_ORDERS"
        columnNames:
        - "O_ORDERKEY"
        timeOffset:
    DIM_PART_SCD2:
      type: "table-input"
      parameters:
        componentName: "DIM_PART_SCD2"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_PART_SCD2"
        columnNames:
        - "P_SRGKEY"
        - "P_PARTKEY"
        timeOffset:
    DIM_SUPPLIER_SCD2:
      type: "table-input"
      parameters:
        componentName: "DIM_SUPPLIER_SCD2"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_SUPPLIER_SCD2"
        columnNames:
        - "S_SRGKEY"
        - "S_SUPPKEY"
        timeOffset:
    STAGE_LINEITEM:
      type: "table-input"
      parameters:
        componentName: "STAGE_LINEITEM"
        database: "EDW_LAB"
        schema: "STAGE_SCHEMA"
        targetTable: "STAGE_LINEITEM"
        columnNames:
        - "L_ORDERKEY"
        - "L_PARTKEY"
        - "L_SUPPKEY"
        - "L_LINENUMBER"
        - "L_QUANTITY"
        - "L_EXTENDEDPRICE"
        - "L_DISCOUNT"
        - "L_TAX"
        - "L_RETURNFLAG"
        - "L_LINESTATUS"
        - "L_SHIPDATE"
        - "L_COMMITDATE"
        - "L_RECEIPTDATE"
        - "L_SHIPINSTRUCT"
        - "L_SHIPMODE"
        - "L_COMMENT"
        timeOffset:
    Active orders:
      type: "join"
      sources:
      - "DIM_ORDERS"
      - "STAGE_LINEITEM"
      parameters:
        componentName: "Active orders"
        mainTable: "DIM_ORDERS"
        mainTableAlias: "o"
        joins:
        - - "STAGE_LINEITEM"
          - "st"
          - "Left"
        joinExpressions:
        - - "\"o\".\"O_ORDERKEY\"=\"st\".\"L_ORDERKEY\""
          - "o_Left_st"
        columnMappings:
        - - "st.L_ORDERKEY"
          - "L_ORDERKEY"
        - - "st.L_PARTKEY"
          - "L_PARTKEY"
        - - "st.L_SUPPKEY"
          - "L_SUPPKEY"
        - - "st.L_LINENUMBER"
          - "L_LINENUMBER"
        - - "st.L_QUANTITY"
          - "L_QUANTITY"
        - - "st.L_EXTENDEDPRICE"
          - "L_EXTENDEDPRICE"
        - - "st.L_DISCOUNT"
          - "L_DISCOUNT"
        - - "st.L_TAX"
          - "L_TAX"
        - - "st.L_RETURNFLAG"
          - "L_RETURNFLAG"
        - - "st.L_LINESTATUS"
          - "L_LINESTATUS"
        - - "st.L_SHIPDATE"
          - "L_SHIPDATE"
        - - "st.L_COMMITDATE"
          - "L_COMMITDATE"
        - - "st.L_RECEIPTDATE"
          - "L_RECEIPTDATE"
        - - "st.L_SHIPINSTRUCT"
          - "L_SHIPINSTRUCT"
        - - "st.L_SHIPMODE"
          - "L_SHIPMODE"
        - - "st.L_COMMENT"
          - "L_COMMENT"
        - - "o.O_ORDERKEY"
          - "o_O_ORDERKEY"
    Active Parts:
      type: "join"
      sources:
      - "DIM_PART_SCD2"
      - "Active orders"
      parameters:
        componentName: "Active Parts"
        mainTable: "DIM_PART_SCD2"
        mainTableAlias: "p"
        joins:
        - - "Active orders"
          - "sl"
          - "Left"
        joinExpressions:
        - - "\"p\".\"P_PARTKEY\"=\"sl\".\"L_PARTKEY\""
          - "p_Left_sl"
        columnMappings:
        - - "p.P_SRGKEY"
          - "P_SRGKEY"
        - - "p.P_PARTKEY"
          - "P_PARTKEY"
        - - "sl.L_ORDERKEY"
          - "L_ORDERKEY"
        - - "sl.L_PARTKEY"
          - "L_PARTKEY"
        - - "sl.L_SUPPKEY"
          - "L_SUPPKEY"
        - - "sl.L_LINENUMBER"
          - "L_LINENUMBER"
        - - "sl.L_QUANTITY"
          - "L_QUANTITY"
        - - "sl.L_EXTENDEDPRICE"
          - "L_EXTENDEDPRICE"
        - - "sl.L_DISCOUNT"
          - "L_DISCOUNT"
        - - "sl.L_TAX"
          - "L_TAX"
        - - "sl.L_RETURNFLAG"
          - "L_RETURNFLAG"
        - - "sl.L_LINESTATUS"
          - "L_LINESTATUS"
        - - "sl.L_SHIPDATE"
          - "L_SHIPDATE"
        - - "sl.L_COMMITDATE"
          - "L_COMMITDATE"
        - - "sl.L_RECEIPTDATE"
          - "L_RECEIPTDATE"
        - - "sl.L_SHIPINSTRUCT"
          - "L_SHIPINSTRUCT"
        - - "sl.L_SHIPMODE"
          - "L_SHIPMODE"
        - - "sl.L_COMMENT"
          - "L_COMMENT"
        - - "sl.o_O_ORDERKEY"
          - "sl.o_O_ORDERKEY"
    Active Suppliers:
      type: "join"
      sources:
      - "DIM_SUPPLIER_SCD2"
      - "Active Parts"
      parameters:
        componentName: "Active Suppliers"
        mainTable: "DIM_SUPPLIER_SCD2"
        mainTableAlias: "s"
        joins:
        - - "Active Parts"
          - "p"
          - "Left"
        joinExpressions:
        - - "\"p\".\"L_SUPPKEY\"=\"s\".\"S_SUPPKEY\""
          - "s_Left_p"
        columnMappings:
        - - "p.L_ORDERKEY"
          - "L_ORDERKEY"
        - - "p.L_PARTKEY"
          - "L_PARTKEY"
        - - "p.L_SUPPKEY"
          - "L_SUPPKEY"
        - - "p.L_LINENUMBER"
          - "L_LINENUMBER"
        - - "p.L_QUANTITY"
          - "L_QUANTITY"
        - - "p.L_EXTENDEDPRICE"
          - "L_EXTENDEDPRICE"
        - - "p.L_DISCOUNT"
          - "L_DISCOUNT"
        - - "p.L_TAX"
          - "L_TAX"
        - - "p.L_RETURNFLAG"
          - "L_RETURNFLAG"
        - - "p.L_LINESTATUS"
          - "L_LINESTATUS"
        - - "p.L_SHIPDATE"
          - "L_SHIPDATE"
        - - "p.L_COMMITDATE"
          - "L_COMMITDATE"
        - - "p.L_RECEIPTDATE"
          - "L_RECEIPTDATE"
        - - "p.L_SHIPINSTRUCT"
          - "L_SHIPINSTRUCT"
        - - "p.L_SHIPMODE"
          - "L_SHIPMODE"
        - - "p.L_COMMENT"
          - "L_COMMENT"
        - - "s.S_SRGKEY"
          - "S_SRGKEY"
        - - "s.S_SUPPKEY"
          - "S_SUPPKEY"
        - - "p.P_SRGKEY"
          - "p.P_SRGKEY"
        - - "p.P_PARTKEY"
          - "p.P_PARTKEY"
        - - "p.sl.o_O_ORDERKEY"
          - "o_O_ORDERKEY"
    Supplier_sk:
      type: "calculator"
      sources:
      - "Active Suppliers"
      parameters:
        componentName: "Supplier_sk"
        includeInputColumns: "Yes"
        calculations:
        - - "CASE When \"S_SUPPKEY\" is null then\r\n-1\r\nelse \r\n\"S_SRGKEY\"\r\
            \nend\r\n"
          - "v_supp_sk"
        - - "CASE When \"p.P_PARTKEY\" is null then\r\n-1\r\nelse \r\n\"p.P_SRGKEY\"\
            \r\nend\r\n"
          - "v_part_sk"
        - - "CASE When \"o_O_ORDERKEY\" is null then\r\n-1\r\nelse \r\n\"o_O_ORDERKEY\"\
            \r\nend\r\n"
          - "v_order_sk"
    FACT_LINEITEM:
      type: "table-output"
      sources:
      - "Combine all sources"
      parameters:
        componentName: "FACT_LINEITEM"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "FACT_LINEITEM"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "v_order_sk"
          - "L_ORDERKEY"
        - - "v_part_sk"
          - "L_PART_SK"
        - - "v_supp_sk"
          - "L_SUPPLIER_SK"
        - - "Line_number"
          - "L_LNIE_NUMBER"
        - - "L_QUANTITY"
          - "L_QUANTITY"
        - - "L_EXTENDEDPRICE"
          - "L_EXTENDEDPRICE"
        - - "L_DISCOUNT"
          - "L_DISCOUNT"
        - - "L_TAX"
          - "L_TAX"
        - - "J.FLAG_JUNK_ID"
          - "JUNK_ID"
        - - "L_SHIPDATE"
          - "L_SHIPDATE"
        - - "L_COMMITDATE"
          - "L_COMMITDATE"
        - - "L_RECEIPTDATE"
          - "L_RECEIPTDATE"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Genarate line numbers:
      type: "rank"
      sources:
      - "DIM_ORDERS"
      parameters:
        componentName: "Genarate line numbers"
        includeInputColumns: "Yes"
        partitionData:
        - "O_ORDERKEY"
        orderingWithinPartitions:
        - - "O_ORDERKEY"
          - "Ascending"
        functions:
        - - "Row Number"
          - "Line_number"
    Combine all sources:
      type: "unite"
      sources:
      - "Genarate line numbers"
      - "Supplier_sk"
      - "STAGE_LINEITEM"
      - "Join the Junk dim"
      parameters:
        componentName: "Combine all sources"
        method: "All Columns"
        castTypes: "Yes"
        addSourceComponentColumn: "No"
        removeDuplicates: "No"
    JUNK_FLAG_DIM:
      type: "table-input"
      parameters:
        componentName: "JUNK_FLAG_DIM"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "JUNK_FLAG_DIM"
        columnNames:
        - "FLAG_JUNK_ID"
        - "L_SHIPINSTRUCT"
        - "L_SHIPMODE"
        - "L_RETURNFLAG"
        - "L_LINESTATUS"
        - "ACTIVE_FLAG"
        - "UPDATED_DATE"
        timeOffset:
    Join the Junk dim:
      type: "join"
      sources:
      - "JUNK_FLAG_DIM"
      - "STAGE_LINEITEM"
      parameters:
        componentName: "Join the Junk dim"
        mainTable: "JUNK_FLAG_DIM"
        mainTableAlias: "J"
        joins:
        - - "STAGE_LINEITEM"
          - "L"
          - "Right"
        joinExpressions:
        - - "\"J\".\"L_SHIPINSTRUCT\"=\"L\".\"L_SHIPINSTRUCT\" AND \"J\".\"L_SHIPMODE\"\
            =\"L\".\"L_SHIPMODE\"AND \"L\".\"L_RETURNFLAG\"=\"J\".\"L_RETURNFLAG\"\
            \ AND\"J\".\"L_LINESTATUS\"=\"J\".\"L_LINESTATUS\""
          - "J_Right_L"
        columnMappings:
        - - "J.FLAG_JUNK_ID"
          - "J.FLAG_JUNK_ID"
design:
  components:
    DIM_ORDERS:
      position:
        x: -710
        "y": -240
      tempMetlId: 1
    DIM_PART_SCD2:
      position:
        x: -710
        "y": -150
      tempMetlId: 2
    DIM_SUPPLIER_SCD2:
      position:
        x: -710
        "y": -60
      tempMetlId: 3
    STAGE_LINEITEM:
      position:
        x: -710
        "y": -320
      tempMetlId: 4
    Active orders:
      position:
        x: -520
        "y": -260
      tempMetlId: 5
    Active Parts:
      position:
        x: -390
        "y": -260
      tempMetlId: 6
    Active Suppliers:
      position:
        x: -240
        "y": -260
      tempMetlId: 7
    Supplier_sk:
      position:
        x: -100
        "y": -260
      tempMetlId: 10
    FACT_LINEITEM:
      position:
        x: 220
        "y": -290
      tempMetlId: 11
    Genarate line numbers:
      position:
        x: -350
        "y": -80
      tempMetlId: 12
    Combine all sources:
      position:
        x: 50
        "y": -290
      tempMetlId: 13
    JUNK_FLAG_DIM:
      position:
        x: -710
        "y": -410
      tempMetlId: 14
    Join the Junk dim:
      position:
        x: -270
        "y": -420
      tempMetlId: 15
