type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "01_trf_sf_stg_customer"
      parameters:
        componentName: "Start"
    Log Customer:
      type: "append-to-grid"
      transitions:
        success:
        - "02_trf_sf_dim_orders_scd1"
        - "Print Variables"
      parameters:
        componentName: "Log Customer"
        operation: "Append"
        targetGridVariable: "gv_load_log_main"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${jv_job_name}"
          - "${sysvar.thisPipeline.fullName}"
          - "1"
          - "Stage_Customer"
          - "Dim_Customer"
          - "${jv_inserted_rows}"
          - "${jv_updated_rows}"
          - "Success"
          - "${jv_start_time}"
          - "${jv_end_time}"
          - "${jv_duration_time}"
          - "Loading the data from Stage to Dimention"
          - "Development"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    "01_trf_sf_stg_customer":
      type: "run-transformation"
      transitions:
        success:
        - "Log Customer"
        failure:
        - "End Failure"
      parameters:
        componentName: "01_trf_sf_stg_customer"
        transformationJob: "Dimentions and Fact/01_trf_sf_dim_customer_scd2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_error_message"
          - "${sysvar.thisComponent.message}"
        - - "jv_inserted_rows"
          - "${(sysvar.childPipeline.vars.jv_inserted_rows) || -1}"
        - - "jv_updated_rows"
          - "${(sysvar.childPipeline.vars.jv_updated_rows) || -1}"
        - - "jv_duration_time"
          - "${sysvar.thisComponent.mainTaskDurationMs}"
        - - "jv_start_time"
          - "${sysvar.thisComponent.startedAt}"
        - - "jv_end_time"
          - "${sysvar.thisComponent.mainTaskFinishedAt}"
        - - "jv_job_name"
          - "${sysvar.thisPipeline.fullName}"
        - - "jv_component_name"
          - "${sysvar.thisComponent.name}"
    "02_trf_sf_dim_orders_scd1":
      type: "run-transformation"
      transitions:
        success:
        - "Log Orders"
        failure:
        - "End Failure 2"
      parameters:
        componentName: "02_trf_sf_dim_orders_scd1"
        transformationJob: "Dimentions and Fact/02_trf_sf_dim_orders_scd1.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_error_message"
          - "${sysvar.thisComponent.message}"
        - - "jv_inserted_rows"
          - "${(sysvar.childPipeline.vars.jv_inserted_rows) || -1}  "
        - - "jv_duration_time"
          - "${sysvar.thisComponent.mainTaskDurationMs}"
        - - "jv_updated_rows"
          - "${(sysvar.childPipeline.vars.jv_updated_rows) || -1}  "
    Log Orders:
      type: "append-to-grid"
      transitions:
        success:
        - "Print Variables 2"
        - "Log Insert"
      parameters:
        componentName: "Log Orders"
        operation: "Append"
        targetGridVariable: "gv_load_log_main"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${jv_job_name}"
          - "${sysvar.thisPipeline.fullName}"
          - "1"
          - "Stage_Customer"
          - "Dim_Customer"
          - "${jv_inserted_rows}"
          - "${jv_updated_rows}"
          - "Success"
          - "${jv_start_time}"
          - "${jv_end_time}"
          - "${jv_duration_time}"
          - "Loading the data from Stage to Dimention"
          - "Development"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Failure 2:
      type: "end-failure"
      parameters:
        componentName: "End Failure 2"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables:
      type: "print-variables"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "gv_load_log_main"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 2:
      type: "print-variables"
      parameters:
        componentName: "Print Variables 2"
        variablesToPrint:
        - - "gv_load_log_main"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Insert:
      type: "run-orchestration"
      parameters:
        componentName: "Log Insert"
        orchestrationJob: "01_orc_job_status_log.orch.yaml"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_load_log_parent"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_load_log_main"
              columns:
              - "jv_load_id"
              - "jv_job_name"
              - "jv_main_job_name"
              - "jv_source_system_id"
              - "jv_source_object_name"
              - "jv_target_object_name"
              - "jv_inserted_rows"
              - "jv_updated_rows"
              - "jv_status"
              - "jv_start_time"
              - "jv_execution_time"
              - "jv_last_run_time"
              - "jv_comment"
              - "jv_environment"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_component_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_duration_time:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_end_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    gv_load_log_main:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          jv_load_id:
            columnType: "TEXT"
          jv_job_name:
            columnType: "TEXT"
          jv_main_job_name:
            columnType: "TEXT"
          jv_source_system_id:
            columnType: "NUMBER"
          jv_source_object_name:
            columnType: "NUMBER"
          jv_target_object_name:
            columnType: "TEXT"
          jv_inserted_rows:
            columnType: "NUMBER"
          jv_updated_rows:
            columnType: "NUMBER"
          jv_status:
            columnType: "TEXT"
          jv_start_time:
            columnType: "TEXT"
          jv_execution_time:
            columnType: "TEXT"
          jv_last_run_time:
            columnType: "TEXT"
          jv_comment:
            columnType: "TEXT"
          jv_environment:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -570
        "y": -90
      tempMetlId: 1
    Log Customer:
      position:
        x: -300
        "y": -90
      tempMetlId: 4
    End Success:
      position:
        x: 290
        "y": -90
      tempMetlId: 12
    "01_trf_sf_stg_customer":
      position:
        x: -440
        "y": -90
      tempMetlId: 14
    "02_trf_sf_dim_orders_scd1":
      position:
        x: -150
        "y": -90
      tempMetlId: 16
    Log Orders:
      position:
        x: -20
        "y": -90
      tempMetlId: 18
    End Failure:
      position:
        x: -370
        "y": 0
      tempMetlId: 19
    End Failure 2:
      position:
        x: -30
        "y": 20
      tempMetlId: 20
    Print Variables:
      position:
        x: -190
        "y": -220
      tempMetlId: 21
    Print Variables 2:
      position:
        x: 140
        "y": -210
      tempMetlId: 22
    Log Insert:
      position:
        x: 140
        "y": -90
      tempMetlId: 23
