type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "t_Stg_Customer_to_Dim_Customer_Scd2"
      parameters:
        componentName: "Start"
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables:
      type: "print-variables"
      transitions:
        failure:
        - "Append To Grid 2 2"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "jv_error_message"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Append 1:
      type: "append-to-grid"
      transitions:
        success:
        - "t_Stg_Supplier_to_Dim_Supplier_Scd2"
      parameters:
        componentName: "Log Append 1"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${jv_job_name}"
          - "${sysvar.thisPipeline.fullName}"
          - "1"
          - "Stage_Customer"
          - "Dim_Customer"
          - "${jv_inserted_rows}"
          - "${jv_updated_rows}"
          - "Success"
          - "${jv_start_time}"
          - "${jv_end_time}"
          - "${jv_duration}"
          - "${sysvar.thisComponent.startedAt}"
          - ""
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Shared Pipeline:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "End Success"
      parameters:
        componentName: "Run Shared Pipeline"
        pipelineName: "EDW_LAB#Load_log_scd2_orc-1"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_parent_load_log_scd2"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_main_job_load_log_scd2"
              columns:
              - "jv_load_id"
              - "jv_job_name"
              - "jv_table_name"
              - "jv_inserted_rows"
              - "jv_updated_rows"
              - "jv_status"
              - "jv_start_time"
              - "jv_end_time"
              - "jv_error_message"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 3:
      type: "print-variables"
      transitions:
        success:
        - "Run Shared Pipeline"
      skipped: false
      parameters:
        componentName: "Print Variables 3"
        variablesToPrint:
        - - "gv_main_job_load_log_scd2"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Append To Grid 2 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Run Shared Pipeline 2"
      parameters:
        componentName: "Append To Grid 2 2"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${sysvar.thisPipeline.fullName}"
          - "stage customer to dim_cust"
          - "${jv_inserted_rows}"
          - "${jv_updated_rows}"
          - "Failed"
          - ""
          - " ${sysvar.thisComponent.startedAt}"
          - "${jv_error_message}"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Shared Pipeline 2:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "End Failure"
      parameters:
        componentName: "Run Shared Pipeline 2"
        pipelineName: "EDW_LAB#Load_log_scd2_orc-1"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_parent_load_log_scd2"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_main_job_load_log_scd2"
              columns:
              - "jv_load_id"
              - "jv_job_name"
              - "jv_table_name"
              - "jv_inserted_rows"
              - "jv_updated_rows"
              - "jv_status"
              - "jv_start_time"
              - "jv_end_time"
              - "jv_error_message"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    t_Stg_Customer_to_Dim_Customer_Scd2:
      type: "run-transformation"
      transitions:
        success:
        - "Log Append 1"
      parameters:
        componentName: "t_Stg_Customer_to_Dim_Customer_Scd2"
        transformationJob: "Dimentions and Fact/t_Stg_Customer_to_Dim_Customer_Scd2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_error_message"
          - "${sysvar.thisComponent.message}"
        - - "jv_inserted_rows"
          - "${sysvar.childPipeline.vars.jv_inserted_rows}"
        - - "jv_updated_rows"
          - "${(sysvar.childPipeline.vars.jv_updated_rows) || -1}"
        - - "jv_start_time"
          - "${sysvar.thisComponent.startedAt}"
        - - "jv_end_time"
          - "${sysvar.thisComponent.mainTaskFinishedAt}"
        - - "jv_duration_time"
          - "${sysvar.thisComponent.mainTaskDurationMs}"
    t_Stg_Supplier_to_Dim_Supplier_Scd2:
      type: "run-transformation"
      transitions:
        success:
        - "Log Append 1 3"
      parameters:
        componentName: "t_Stg_Supplier_to_Dim_Supplier_Scd2"
        transformationJob: "Dimentions and Fact/t_Stg_Supplier_to_Dim_Supplier_Scd2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_error_message"
          - "${sysvar.thisComponent.message}"
        - - "jv_inserted_rows"
          - "${sysvar.childPipeline.vars.jv_inserted_rows}"
        - - "jv_updated_rows"
          - "${(sysvar.childPipeline.vars.jv_updated_rows) || -1}"
        - - "jv_start_time"
          - "${sysvar.thisComponent.startedAt}"
        - - "jv_end_time"
          - "${sysvar.thisComponent.mainTaskFinishedAt}"
        - - "jv_duration_time"
          - "${sysvar.thisComponent.mainTaskDurationMs}"
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - "Log Append 1 3 2"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "Dimentions and Fact/t_Stg_Part_to_Dim_Part_Scd2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Append 1 3:
      type: "append-to-grid"
      transitions:
        success:
        - "Run Transformation"
      parameters:
        componentName: "Log Append 1 3"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${jv_job_name}"
          - "${sysvar.thisPipeline.fullName}"
          - "1"
          - "Stage_Spplier"
          - "Dim_Supllier"
          - "${jv_inserted_rows}"
          - "${jv_updated_rows}"
          - "Success"
          - "${jv_start_time}"
          - "${jv_end_time}"
          - "${jv_duration}"
          - "${sysvar.thisComponent.startedAt}"
          - ""
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Append 1 3 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Print Variables 3"
      parameters:
        componentName: "Log Append 1 3 2"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${jv_job_name}"
          - "${sysvar.thisPipeline.fullName}"
          - "1"
          - "Stage_Spplier"
          - "Dim_Supllier"
          - "${jv_inserted_rows}"
          - "${jv_updated_rows}"
          - "Success"
          - "${jv_start_time}"
          - "${jv_end_time}"
          - "${jv_duration}"
          - "${sysvar.thisComponent.startedAt}"
          - ""
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_duration:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    Execution_Time:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Error in parent"
    p_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_last_run_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_end_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    gv_parent_load_log_scd2:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          jv_load_id:
            columnType: "TEXT"
          jv_job_name:
            columnType: "TEXT"
          jv_table_name:
            columnType: "TEXT"
          jv_inserted_rows:
            columnType: "NUMBER"
          jv_updated_rows:
            columnType: "NUMBER"
          jv_status:
            columnType: "TEXT"
          jv_start_time:
            columnType: "TEXT"
          jv_end_time:
            columnType: "TEXT"
          jv_error_message:
            columnType: "TEXT"
      defaultValue: []
    gv_main_job_load_log_scd2:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          jv_load_id:
            columnType: "TEXT"
          jv_job_name:
            columnType: "TEXT"
          jv_main_job_name:
            columnType: "TEXT"
          jv_source_system_id:
            columnType: "NUMBER"
          jv_source_object_name:
            columnType: "NUMBER"
          jv_target_object_name:
            columnType: "TEXT"
          jv_inserted_rows:
            columnType: "NUMBER"
          jv_updated_rows:
            columnType: "NUMBER"
          jv_status:
            columnType: "TEXT"
          jv_start_time:
            columnType: "TEXT"
          jv_end_time:
            columnType: "TEXT"
          jv_execution_time:
            columnType: "TEXT"
          jv_last_run_time:
            columnType: "TEXT"
          jv_created_log_at:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -380
        "y": 30
      tempMetlId: 1
    End Success:
      position:
        x: 730
        "y": 30
      tempMetlId: 6
    End Failure:
      position:
        x: 700
        "y": 170
      tempMetlId: 7
    Print Variables:
      position:
        x: 380
        "y": 210
      tempMetlId: 9
    Log Append 1:
      position:
        x: -110
        "y": 30
      tempMetlId: 12
    Run Shared Pipeline:
      position:
        x: 610
        "y": 30
      tempMetlId: 13
    Print Variables 3:
      position:
        x: 470
        "y": 30
      tempMetlId: 14
    Append To Grid 2 2:
      position:
        x: 490
        "y": 120
      tempMetlId: 15
    Run Shared Pipeline 2:
      position:
        x: 590
        "y": 170
      tempMetlId: 16
    t_Stg_Customer_to_Dim_Customer_Scd2:
      position:
        x: -260
        "y": 30
      tempMetlId: 21
    t_Stg_Supplier_to_Dim_Supplier_Scd2:
      position:
        x: 10
        "y": 30
      tempMetlId: 22
    Run Transformation:
      position:
        x: 250
        "y": 30
      tempMetlId: 24
    Log Append 1 3:
      position:
        x: 140
        "y": 30
      tempMetlId: 25
    Log Append 1 3 2:
      position:
        x: 370
        "y": 0
      tempMetlId: 26
