type: "transformation"
version: "1.0"
pipeline:
  components:
    STG_PARTT_SCD2:
      type: "table-input"
      parameters:
        componentName: "STG_PARTT_SCD2"
        database: "EDW_LAB"
        schema: "STAGE_SCHEMA"
        targetTable: "STAGE_PART_SCD2"
        columnNames:
        - "P_PARTKEY"
        - "P_NAME"
        - "P_MFGR"
        - "P_BRAND"
        - "P_TYPE"
        - "P_SIZE"
        - "P_CONTAINER"
        - "P_RETAILPRICE"
        - "P_COMMENT"
        - "START_TIME"
        timeOffset:
    Detect Changes:
      type: "detect-changes"
      sources:
      - "Filter"
      - "Current Data of Target"
      parameters:
        componentName: "Detect Changes"
        masterTable: "Current Data of Target"
        matchKeys:
        - "P_PARTKEY"
        compareColumns:
        - "P_PARTKEY"
        - "P_NAME"
        - "P_MFGR"
        - "P_BRAND"
        - "P_TYPE"
        - "P_SIZE"
        - "P_CONTAINER"
        - "P_RETAILPRICE"
        - "P_COMMENT"
        outputColumnMapping:
        - - "compare_P_PARTKEY"
          - "compare_P_PARTKEY"
        - - "compare_P_NAME"
          - "compare_P_NAME"
        - - "compare_P_MFGR"
          - "compare_P_MFGR"
        - - "compare_P_BRAND"
          - "compare_P_BRAND"
        - - "compare_P_TYPE"
          - "compare_P_TYPE"
        - - "compare_P_SIZE"
          - "compare_P_SIZE"
        - - "compare_P_CONTAINER"
          - "compare_P_CONTAINER"
        - - "compare_P_RETAILPRICE"
          - "compare_P_RETAILPRICE"
        - - "compare_P_COMMENT"
          - "compare_P_COMMENT"
        - - "compare_START_TIME"
          - "NEW_LOAD"
        indicatorColumn: "Indicator"
    Rank:
      type: "rank"
      sources:
      - "STG_PARTT_SCD2"
      parameters:
        componentName: "Rank"
        includeInputColumns: "Yes"
        partitionData:
        - "P_PARTKEY"
        - "P_NAME"
        - "P_MFGR"
        - "P_BRAND"
        - "P_TYPE"
        - "P_SIZE"
        - "P_CONTAINER"
        - "P_RETAILPRICE"
        - "P_COMMENT"
        - "START_TIME"
        orderingWithinPartitions:
        - - "START_TIME"
          - "Descending"
        functions:
        - - "Row Number"
          - "rn"
    Filter:
      type: "filter"
      sources:
      - "Rank"
      parameters:
        componentName: "Filter"
        filterConditions:
        - - "rn"
          - "Is"
          - "Equal to"
          - "1"
        combineCondition: "And"
    Current Data of Target:
      type: "sql"
      parameters:
        componentName: "Current Data of Target"
        query: "SELECT * FROM ANALYTICS_DB.ANALYTICS_SCHEMA.DIM_PART_SCD2 WHERE P_END_TIME\
          \ IS NULL"
    New data:
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "New data"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "N"
        combineCondition: "Or"
    update:
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "update"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "C"
        combineCondition: "And"
    DIM_PART_SCD2_UPDATE:
      type: "table-output"
      sources:
      - "Calculator 2"
      parameters:
        componentName: "DIM_PART_SCD2_UPDATE"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_PART_SCD2"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "P_PARTKEY"
          - "P_PARTKEY"
        - - "compare_P_NAME"
          - "P_NAME"
        - - "compare_P_MFGR"
          - "P_MFGR"
        - - "compare_P_BRAND"
          - "P_BRAND"
        - - "compare_P_TYPE"
          - "P_TYPE"
        - - "compare_P_SIZE"
          - "P_SIZE"
        - - "compare_P_CONTAINER"
          - "P_CONTAINER"
        - - "compare_P_RETAILPRICE"
          - "P_RETAILPRICE"
        - - "compare_P_COMMENT"
          - "P_COMMENT"
        - - "LOAD_TIME_V"
          - "P_LOAD_TIME"
        - - "END_TIME_UP_V"
          - "P_END_TIME"
        - - "ACTIVE_FLAG"
          - "P_ACTIVE_FLAG"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    DIM_PART_INSERT_SCD2:
      type: "table-output"
      sources:
      - "Calculator"
      parameters:
        componentName: "DIM_PART_INSERT_SCD2"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_PART_SCD2"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "P_PARTKEY"
          - "P_PARTKEY"
        - - "compare_P_NAME"
          - "P_NAME"
        - - "compare_P_MFGR"
          - "P_MFGR"
        - - "compare_P_BRAND"
          - "P_BRAND"
        - - "compare_P_TYPE"
          - "P_TYPE"
        - - "compare_P_SIZE"
          - "P_SIZE"
        - - "compare_P_CONTAINER"
          - "P_CONTAINER"
        - - "compare_P_RETAILPRICE"
          - "P_RETAILPRICE"
        - - "compare_P_COMMENT"
          - "P_COMMENT"
        - - "LOAD_TIME_V"
          - "P_LOAD_TIME"
        - - "END_TIME_IN_V"
          - "P_END_TIME"
        - - "ACTIVE_FLAG"
          - "P_ACTIVE_FLAG"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Calculator:
      type: "calculator"
      sources:
      - "New data"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "LOAD_TIME_V"
        - - "NULL"
          - "END_TIME_IN_V"
        - - "'Y'"
          - "ACTIVE_FLAG"
    Calculator 2:
      type: "calculator"
      sources:
      - "update"
      parameters:
        componentName: "Calculator 2"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "LOAD_TIME_V"
        - - "NULL"
          - "END_TIME_UP_V"
        - - "'Y'"
          - "ACTIVE_FLAG"
    DIM_PRODUCT_SCD2 2:
      type: "table-update"
      sources:
      - "Calculator 3"
      parameters:
        componentName: "DIM_PRODUCT_SCD2 2"
        warehouse: "[Environment Default]"
        database: "ANALYTICS_DB"
        schema: "ANALYTICS_SCHEMA"
        targetTable: "DIM_PART_SCD2"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"input\".\"P_PARTKEY\"=\"target\".\"P_PARTKEY\" AND \"target\".\"P_END_TIME\"\
            \ IS NULL AND\"input\".\"NEW_LOAD\">\"target\".\"P_LOAD_TIME\""
          - "Case"
        whenMatched:
        - - "\"input\".\"P_PARTKEY\"=\"target\".\"P_PARTKEY\" AND \"target\".\"P_END_TIME\"\
            \ IS NULL AND\"input\".\"NEW_LOAD\">\"target\".\"P_LOAD_TIME\""
          - "Update"
        updateMapping:
        - - "END_TIME_OLD"
          - "P_END_TIME"
        - - "AVTIVE_FLAG"
          - "P_ACTIVE_FLAG"
        includeNotMatched: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Calculator 3:
      type: "calculator"
      sources:
      - "update"
      parameters:
        componentName: "Calculator 3"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "END_TIME_OLD"
        - - "'N'"
          - "AVTIVE_FLAG"
  variables:
    jv_updated_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "failed meesage"
design:
  components:
    STG_PARTT_SCD2:
      position:
        x: -730
        "y": -180
      tempMetlId: 1
    Detect Changes:
      position:
        x: -350
        "y": -100
      tempMetlId: 3
    Rank:
      position:
        x: -610
        "y": -180
      tempMetlId: 4
    Filter:
      position:
        x: -490
        "y": -180
      tempMetlId: 5
    Current Data of Target:
      position:
        x: -710
        "y": 0
      tempMetlId: 6
    New data:
      position:
        x: -190
        "y": -180
      tempMetlId: 7
    update:
      position:
        x: -230
        "y": -10
      tempMetlId: 8
    DIM_PART_SCD2_UPDATE:
      position:
        x: 210
        "y": -50
      tempMetlId: 9
    DIM_PART_INSERT_SCD2:
      position:
        x: 170
        "y": -180
      tempMetlId: 10
    Calculator:
      position:
        x: 10
        "y": -180
      tempMetlId: 11
    Calculator 2:
      position:
        x: 10
        "y": -50
      tempMetlId: 12
    DIM_PRODUCT_SCD2 2:
      position:
        x: 230
        "y": 100
      tempMetlId: 19
    Calculator 3:
      position:
        x: -10
        "y": 90
      tempMetlId: 20
