type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Append To Grid"
      parameters:
        componentName: "Start"
    End Success:
      type: "end-success"
      parameters:
        componentName: "End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    End Failure:
      type: "end-failure"
      parameters:
        componentName: "End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables:
      type: "print-variables"
      transitions:
        success:
        - "Append To Grid 2 2"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "p_error_message"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Append To Grid:
      type: "append-to-grid"
      transitions:
        success:
        - "Print Variables 2"
      parameters:
        componentName: "Append To Grid"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${sysvar.thisPipeline.fullName}"
          - "Stage customer to Dim Customer"
          - "0"
          - "0"
          - "Job is  started"
          - "${sysvar.thisComponent.startedAt}"
          - "-1"
          - "meesage"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 2:
      type: "print-variables"
      transitions:
        success:
        - "Run Transformation"
      parameters:
        componentName: "Print Variables 2"
        variablesToPrint:
        - - "gv_main_job_load_log_scd2"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Append To Grid 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Print Variables 3"
      parameters:
        componentName: "Append To Grid 2"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${sysvar.thisPipeline.fullName}"
          - "stage customer to dim_cust"
          - "${v_inserted_rows1}"
          - "${v_updated_rows1}"
          - "Job is Completed"
          - "${sysvar.thisComponent.startedAt}"
          - "${sysvar.thisComponent.startedAt}"
          - "${v_error_message}"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Shared Pipeline:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "End Success"
      parameters:
        componentName: "Run Shared Pipeline"
        pipelineName: "EDW_LAB#Load_log_scd2_orc-1"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_parent_load_log_scd2"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_main_job_load_log_scd2"
              columns:
              - "jv_load_id"
              - "jv_job_name"
              - "jv_table_name"
              - "jv_inserted_rows"
              - "jv_updated_rows"
              - "jv_status"
              - "jv_start_time"
              - "jv_end_time"
              - "jv_error_message"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 3:
      type: "print-variables"
      transitions:
        success:
        - "Run Shared Pipeline"
      parameters:
        componentName: "Print Variables 3"
        variablesToPrint:
        - - "gv_main_job_load_log_scd2"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Append To Grid 2 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Run Shared Pipeline 2"
      parameters:
        componentName: "Append To Grid 2 2"
        operation: "Append"
        targetGridVariable: "gv_main_job_load_log_scd2"
        valuesGrid:
        - - "${sysvar.thisPipeline.executionId}"
          - "${sysvar.thisPipeline.fullName}"
          - "stage customer to dim_cust"
          - "${v_inserted_rows}"
          - "${v_updated_rows}"
          - "Failed"
          - "${sysvar.thisComponent.startedAt}"
          - " ${sysvar.thisComponent.startedAt}"
          - "${p_error_message}"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Shared Pipeline 2:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "End Failure"
      parameters:
        componentName: "Run Shared Pipeline 2"
        pipelineName: "EDW_LAB#Load_log_scd2_orc-1"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_parent_load_log_scd2"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_main_job_load_log_scd2"
              columns:
              - "jv_load_id"
              - "jv_job_name"
              - "jv_table_name"
              - "jv_inserted_rows"
              - "jv_updated_rows"
              - "jv_status"
              - "jv_start_time"
              - "jv_end_time"
              - "jv_error_message"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Python Pushdown:
      type: "python-pushdown"
      transitions:
        success:
        - "Print Variables"
      parameters:
        componentName: "Python Pushdown"
        warehouse: "[Environment Default]"
        externalAccessIntegrations:
        pythonVersion: "3.10"
        packagesGrid:
        scriptLocation: "Component"
        pythonScript: |-
          ###
          # Variables are directly accessible:
          #   print (myvar)
          # Updating a variable:
          #   context.updateVariable('myvar', 'new-value')
          # Updating a grid variable:
          #   context.updateGridVariable('mygridvar',[['list','of'],['lists','!']])
          # Running SQL against Snowflake
          #   session.sql('CREATE sample_product_data (id INT, name VARCHAR, serial_number VARCHAR)').collect()
          # Using Data Frames
          #   See here: https://docs.snowflake.com/en/developer-guide/snowpark/python/working-with-dataframes
          ###)
          context.updateVariable(p_error_message,v_error_message)
          print(p_error_message)
        scriptTimeout: "360"
      postProcessing:
        updateOutputMessage: "p_error_message"
        updateScalarVariables:
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - "Append To Grid 2"
        failure:
        - "Python Pushdown"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "Dimentions and Fact/t_Stg_Customer_to_Dim_Customer_Scd2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_inserted_rows1"
          - "${sysvar.childPipeline.vars.jv_inserted_rows}"
        - - "v_updated_rows1"
          - "${sysvar.childPipeline.vars.jv_updated_rows}"
  variables:
    v_inserted_rows1:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Error in parent"
    p_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_updated_rows1:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    gv_parent_load_log_scd2:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          jv_load_id:
            columnType: "TEXT"
          jv_job_name:
            columnType: "TEXT"
          jv_table_name:
            columnType: "TEXT"
          jv_inserted_rows:
            columnType: "NUMBER"
          jv_updated_rows:
            columnType: "NUMBER"
          jv_status:
            columnType: "TEXT"
          jv_start_time:
            columnType: "TEXT"
          jv_end_time:
            columnType: "TEXT"
          jv_error_message:
            columnType: "TEXT"
      defaultValue: []
    gv_main_job_load_log_scd2:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          jv_load_id:
            columnType: "TEXT"
          jv_job_name:
            columnType: "TEXT"
          jv_table_name:
            columnType: "TEXT"
          jv_inserted_rows:
            columnType: "NUMBER"
          jv_updated_rows:
            columnType: "NUMBER"
          jv_status:
            columnType: "TEXT"
          jv_start_time:
            columnType: "TEXT"
          jv_end_time:
            columnType: "TEXT"
          jv_error_message:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -380
        "y": 30
      tempMetlId: 1
    End Success:
      position:
        x: 690
        "y": -70
      tempMetlId: 6
    End Failure:
      position:
        x: 720
        "y": 60
      tempMetlId: 7
    Print Variables:
      position:
        x: 360
        "y": 60
      tempMetlId: 9
    Append To Grid:
      position:
        x: -280
        "y": 30
      tempMetlId: 10
    Print Variables 2:
      position:
        x: -160
        "y": 30
      tempMetlId: 11
    Append To Grid 2:
      position:
        x: 230
        "y": -70
      tempMetlId: 12
    Run Shared Pipeline:
      position:
        x: 540
        "y": -70
      tempMetlId: 13
    Print Variables 3:
      position:
        x: 390
        "y": -70
      tempMetlId: 14
    Append To Grid 2 2:
      position:
        x: 470
        "y": 60
      tempMetlId: 15
    Run Shared Pipeline 2:
      position:
        x: 590
        "y": 60
      tempMetlId: 16
    Python Pushdown:
      position:
        x: 250
        "y": 60
      tempMetlId: 20
    Run Transformation:
      position:
        x: 0
        "y": 30
      tempMetlId: 21
