type: "orchestration"
version: "1.0"
pipeline:
  components:
    Error_log_insert 0:
      type: "unknown-orchestration"
      transitions:
        success:
        - "End Failure 0"
      skipped: false
      parameters:
        "1": "Error_log_insert 0"
        "2":
        - "1":
          - - "gv_error_log"
        - "1":
          - - "gv_load_id"
            - "gv_job_name"
            - "gv_job_parent"
            - "gv_table_name"
            - "gv_table_type"
            - "gv_error_rows"
            - "gv_subject_area"
            - "gv_process_date"
            - "gv_start_time"
            - "gv_run_history_id"
            - "gv_status"
            - "gv_error_message"
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Main ETL Log Entry Start"
      skipped: false
      parameters:
        componentName: "Start 0"
    End Success 0:
      type: "end-success"
      skipped: false
      parameters:
        componentName: "End Success 0"
    Append To Grid error log for main job:
      type: "append-to-grid"
      transitions:
        success:
        - "Error_log_insert 0"
      skipped: false
      parameters:
        componentName: "Append To Grid error log for main job"
        operation: "Append"
        targetGridVariable: "gv_error_log"
        fixedGridMode: "Fixed"
        valuesGrid:
        - - "${jv_load_id}"
          - "${sysvar.thisPipeline.fullName}"
          - "-1"
          - "-1"
          - "-1"
          - "0"
          - "0"
          - "${jv_subject_area}"
          - "${jv_process_date}"
          - "${jv_success_flag}"
          - "${jv_start_time}"
          - "${jv_end_time}"
          - "0"
          - "${sysvar.rootPipeline.executionId}"
          - "${jv_status}"
          - "${jv_error_message}"
          - "0"
          - "0"
          - "-1"
    End Failure 0:
      type: "end-failure"
      skipped: false
      parameters:
        componentName: "End Failure 0"
    Or 0:
      type: "or"
      transitions:
        unconditional:
        - "Append To Grid error log for main job"
      skipped: false
      parameters:
        componentName: "Or 0"
    Main ETL Log Entry Start:
      type: "sql-script"
      transitions:
        success:
        - "Update control table"
      skipped: false
      parameters:
        componentName: "Main ETL Log Entry Start"
        sqlScript: "insert into ${ev_edp_curated_schema}.load_log \n(LOAD_ID,PROCEDURE_NAME,PROCEDURE_PARENT,TABLE_NAME,TABLE_TYPE,SUBJECT_AREA,\n\
          \ PROCESS_DATE,START_TIME,\n FROMDATEPARAMETER,TODATEPARAMETER,COMMENTS)\n\
          \ \n Values\n\n(${jv_load_id},'${sysvar.thisPipeline.fullName}','None','None','None','${jv_subject_area}',\n\
          \ '${jv_process_date}',current_timestamp(),\n '${jv_last_run_dt}','${jv_curr_run_dt}','MASTER\
          \ ETL for CCT Incremental Load Started')"
    Update control table:
      type: "sql-script"
      transitions:
        success:
        - "Start load grp 2 only"
      skipped: false
      parameters:
        componentName: "Update control table"
        sqlScript: |-
          UPDATE ${ev_edp_curated_schema}.JOB_CONTROL_TABLE
          SET RUN_STATUS = 'Y'
          WHERE RUN_STATUS = 'N'
          AND ACTIVE_STATUS = 'Y'
          AND SUBJECT_AREA = 'CCT'
    CCT Jobs grp 2 only:
      type: "run-orchestration"
      skipped: false
      parameters:
        componentName: "CCT Jobs grp 2 only"
        orchestrationJob: "${jv_control_job_name}"
        setScalarVariables:
        - - "jv_job_parent"
          - "${sysvar.thisPipeline.fullName}"
        - - "jv_subject_area"
          - "${jv_subject_area}"
        - - "jv_curr_run_dt"
          - "${jv_curr_run_dt}"
        - - "jv_last_run_dt"
          - "${jv_last_run_dt}"
        - - "jv_load_id"
          - "${jv_load_id}"
        - - "jv_process_date"
          - "${jv_process_date}"
        setGridVariables:
      postProcessing:
        updateScalarVariables:
        - - "jv_error_message"
          - "${sysvar.childPipeline.vars.jv_error_message}"
    Start load grp 2 only:
      type: "query-to-grid"
      transitions:
        success:
        - "Copy of Grid Iterator 0 (1)"
      skipped: false
      parameters:
        componentName: "Start load grp 2 only"
        mode: "Advanced"
        query: |-
          SELECT JOB_NAME from ${ev_edp_curated_schema}.JOB_CONTROL_TABLE
          WHERE RUN_STATUS = 'Y' AND ACTIVE_STATUS = 'Y' AND SUBJECT_AREA = 'CCT' AND JOB_GROUP = 2 ORDER BY JOB_SEQ
        gridVariable: "gv_control_table"
        gridVariableMapping:
        - - "JOB_NAME"
          - "gv_control_job_name"
    Copy of Grid Iterator 0 (1):
      type: "grid-iterator"
      transitions:
        success:
        - "End Success 0"
        failure:
        - "Or 0"
      iterationTarget: "CCT Jobs grp 2 only"
      skipped: false
      parameters:
        componentName: "Copy of Grid Iterator 0 (1)"
        gridVariable: "gv_control_table"
        gridIteratorVariableMapping:
        - - "gv_control_job_name"
          - "jv_control_job_name"
        breakOnFailure: "Yes"
        concurrency: "Sequential"
  variables:
    jv_seq:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_status:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "None"
    jv_load_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "-1"
    jv_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_end_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-01-01 00:00:00"
    jv_job_parent:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "o_CCT_MAIN_ETL"
    jv_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1970-01-01"
    jv_curr_run_dt:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-10-15"
    jv_last_run_dt:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-08-15"
    jv_process_date:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-01-01"
    jv_subject_area:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "CCT Incremental Load"
    jv_success_flag:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_restart_check:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_act_curr_run_dt:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-08-17"
    jv_act_last_run_dt:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-08-15"
    jv_control_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "o_cur_workforce_participant"
    gv_load_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "NUMBER"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "NUMBER"
          gv_subject_area:
            columnType: "TEXT"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "NUMBER"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_run_history_id:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
          gv_error_rows:
            columnType: "NUMBER"
          gv_error_number:
            columnType: "NUMBER"
          gv_error_message:
            columnType: "TEXT"
          gv_comment:
            columnType: "TEXT"
      defaultValue:
      - - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "1970-01-01"
        - "-1"
        - "1970-01-01"
        - "1970-01-01"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
    gv_error_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "NUMBER"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "NUMBER"
          gv_subject_area:
            columnType: "TEXT"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "NUMBER"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_run_history_id:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
          gv_error_rows:
            columnType: "NUMBER"
          gv_error_number:
            columnType: "NUMBER"
          gv_error_message:
            columnType: "TEXT"
      defaultValue:
      - - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "1970-01-01"
        - "-1"
        - "1970-01-01"
        - "1970-01-01"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
    gv_control_table:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_control_job_name:
            columnType: "TEXT"
      defaultValue: []
    gv_temp_load_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "NUMBER"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "NUMBER"
          gv_subject_area:
            columnType: "TEXT"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "NUMBER"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_run_history_id:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
          gv_error_rows:
            columnType: "NUMBER"
          gv_error_number:
            columnType: "NUMBER"
          gv_error_message:
            columnType: "TEXT"
          gv_comment:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Error_log_insert 0:
      position:
        x: -16
        "y": 240
      tempMetlId: 4689
    Start 0:
      position:
        x: -544
        "y": 32
      tempMetlId: 4690
    End Success 0:
      position:
        x: 192
        "y": 32
      tempMetlId: 4691
    Append To Grid error log for main job:
      position:
        x: -240
        "y": 240
      tempMetlId: 4692
    End Failure 0:
      position:
        x: 192
        "y": 240
      tempMetlId: 4693
    Or 0:
      position:
        x: -448
        "y": 240
      tempMetlId: 4694
    Main ETL Log Entry Start:
      position:
        x: -384
        "y": 32
      tempMetlId: 4695
    Update control table:
      position:
        x: -240
        "y": 32
      tempMetlId: 4696
    CCT Jobs grp 2 only:
      position:
        x: 16
        "y": 64
      tempMetlId: 4697
    Start load grp 2 only:
      position:
        x: -96
        "y": 32
      tempMetlId: 4698
    Copy of Grid Iterator 0 (1):
      position:
        x: 16
        "y": 32
      tempMetlId: 4699
  notes:
    "4684":
      position:
        x: 682
        "y": -98
      size:
        height: 388
        width: 362
      theme: "yellow"
      content: |-
        **"Check run status"** - This is a reusable component which checks whether any previous job is completed/failed then only moves forward otherwise fails.

        **"Update control tables"** - This component sets job_status column in control table to 'Y'.

        **"Start new load"** - This component reads control table gets job name column and sets it into gv_control_table grid variable

        **"Grid iterator/CCTA jobs"** - This component iterates on the job names received from gv_control_table  grid variable
        and executes them in sequential manner.

        **"Setting success flag run_status"** - This component will set jv_run_status variable to 1 on job success and sets it to 0 on job failure.

        **"Update_run_status"** - This is a reusable component which updates job status to success on job success and to failure when job fails and also updates the job end time in run status table.

        **"Append To Grid error log for main job"** - This component appends required values to gv_error_log grid variable when job fails.

        **"Error_log_insert"** - This is a reusable component to write failed entry to error log table.
    "4685":
      position:
        x: -480
        "y": 183
      size:
        height: 116
        width: 716
      theme: "red"
      content: "**FAILURE PATH**"
    "4686":
      position:
        x: -210
        "y": -133
      size:
        height: 230
        width: 739
      theme: "green"
      content: "**SUCCESS PATH**"
    "4687":
      position:
        x: -484
        "y": -240
      size:
        height: 78
        width: 730
      theme: "yellow"
      content: "**Description:** This procedure is the main Procedure that drives\
        \ the entire CCTA Load "
    "4688":
      position:
        x: -735
        "y": -134
      size:
        height: 237
        width: 155
      theme: "yellow"
      content: "\n**VARIABLES USED``**\n\n``GRID VARIABLES\n\n1. gv_load_log\n2. gv_error_log\n\
        3.gv_temp_load_log\n4.gv_control_table\n\nJOB VARIABLES\n\n1.jv_control_job_name\t\
        \n2.jv_job_parent\t\n3.jv_subject_area\t\n4.jv_success_flag\t\n"
