type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Logs append 2"
      parameters:
        componentName: "Start"
    Run Orchestration:
      type: "run-orchestration"
      transitions:
        success:
        - "Mark Job Completed "
        failure:
        - "Mark Job Failed"
      parameters:
        componentName: "Run Orchestration"
        orchestrationJob: "EDW STAGE/${v_current_job_name}"
        setScalarVariables:
        - - "v_current_job_name"
          - "${v_current_job_name}"
        - - "v_current_job_seq"
          - "${v_current_job_seq}"
        - - "v_current_table_name"
          - "${v_current_table_name}"
        setGridVariables:
      postProcessing:
        updateOutputMessage: "Detailed messgae : ${v_detailed_message}"
        updateScalarVariables:
        - - "v_detailed_message"
          - "${sysvar.childPipeline.vars.v_error_message}"
        - - "jv_updated_rows"
          - "${sysvar.childPipile.vars.v_row_count}"
        - - "v_current_table_name"
          - "${sysvar.childPipeline.vars.x_table_name}"
    Mark Job Running:
      type: "sql-executor"
      transitions:
        success:
        - "Run Orchestration"
      parameters:
        componentName: "Mark Job Running"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "UPDATE INTERNAL_TRAINING.EDP_CURATED.job_status \r\nSET STATUS\
          \ = 'RUNNING', \r\n    START_TIME = CURRENT_TIMESTAMP(), \r\n    LAST_UPDATED\
          \ = CURRENT_TIMESTAMP(),\r\n    ERROR_MESSAGE='${v_detailed_message}'\r\n\
          WHERE job_name='${v_current_job_name}'"
      postProcessing:
        updateOutputMessage: "JOB Running : ${v_current_job_name}"
        updateScalarVariables:
    Mark Job Failed:
      type: "sql-executor"
      transitions:
        success:
        - "Append To Grid 2 2 2"
      parameters:
        componentName: "Mark Job Failed"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "UPDATE INTERNAL_TRAINING.EDP_CURATED.job_status \r\nSET STATUS\
          \ = 'FAILED', \r\n    END_TIME = CURRENT_TIMESTAMP(), \r\n    ERROR_MESSAGE='${v_detailed_message}'\r\
          \nWHERE job_name='${v_current_job_name}'"
      postProcessing:
        updateOutputMessage: "JOB FAILED : ${v_current_job_name}"
        updateScalarVariables:
    'Mark Job Completed ':
      type: "sql-executor"
      transitions:
        success:
        - "Logs append 3"
      parameters:
        componentName: "Mark Job Completed "
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "UPDATE INTERNAL_TRAINING.EDP_CURATED.job_status \r\nSET STATUS\
          \ = 'COMPLETED', \r\n    END_TIME = CURRENT_TIMESTAMP(), \r\n    ERROR_MESSAGE='${v_detailed_message}'\r\
          \nWHERE job_name='${v_current_job_name}'"
      postProcessing:
        updateOutputMessage: "JOB Completed : ${v_current_job_name}"
        updateScalarVariables:
    Logs append 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Logs for Running"
      skipped: false
      parameters:
        componentName: "Logs append 2"
        operation: "Append"
        targetGridVariable: "gv_load_log1"
        valuesGrid:
        - - " ${sysvar.thisComponent.taskId}"
          - "${sysvar.thisPipeline.fullName}"
          - "${sysvar.rootPipeline.executionId}"
          - "abc"
          - "table"
          - "0"
          - "0"
          - ""
          - "${new Date().toISOString()}"
          - "Y"
          - "${sysvar.thisComponent.startedAt}"
          - ""
          - "0"
          - "${sysvar.rootPipeline.executionId}"
          - "Jobs running started"
          - "Logs for running jobs"
          - "running"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Logs for Running:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "Mark Job Running"
      skipped: false
      parameters:
        componentName: "Logs for Running"
        pipelineName: "EDW_LAB#load_log_insert_orc"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_load_log"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_load_log1"
              columns:
              - "gv_load_id"
              - "gv_job_name"
              - "gv_job_parent"
              - "gv_table_name"
              - "gv_table_type"
              - "gv_inserted_rows"
              - "gv_updated_rows"
              - "gv_subject_area"
              - "gv_process_date"
              - "gv_success_flag"
              - "gv_start_time"
              - "gv_end_time"
              - "gv_row_count"
              - "gv_run_history_id"
              - "gv_status"
              - "gv_message"
              - "gv_comment"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Append To Grid 2 2 2:
      type: "append-to-grid"
      transitions:
        success:
        - "Run Shared Pipeline 2 2"
      skipped: false
      parameters:
        componentName: "Append To Grid 2 2 2"
        operation: "Append"
        targetGridVariable: "gv_error_log"
        valuesGrid:
        - - " ${sysvar.thisComponent.taskId}"
          - "${sysvar.thisPipeline.fullName}"
          - "${sysvar.rootPipeline.executionId}"
          - "${v_current_table_name}"
          - "table"
          - "0"
          - "0"
          - "${new Date().toISOString()}"
          - "-1"
          - "Y"
          - "${sysvar.thisComponent.startedAt}"
          - "-1"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Run Shared Pipeline 2 2:
      type: "run-shared-pipeline"
      skipped: false
      parameters:
        componentName: "Run Shared Pipeline 2 2"
        pipelineName: "EDW_LAB#error_log_insert_trans1"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_error_log"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_error_log"
              columns:
              - "gv_load_id"
              - "gv_job_name"
              - "gv_job_parent"
              - "gv_table_name"
              - "gv_table_type"
              - "gv_error_rows"
              - "gv_subject_area"
              - "gv_run_date"
              - "gv_run_time"
              - "gv_run_history_id"
              - "gv_status"
              - "gv_message"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Logs append 3:
      type: "append-to-grid"
      transitions:
        success:
        - "Logs for Completed Jobs"
      skipped: false
      parameters:
        componentName: "Logs append 3"
        operation: "Append"
        targetGridVariable: "gv_load_log1"
        valuesGrid:
        - - " ${sysvar.thisComponent.taskId}"
          - "${sysvar.thisPipeline.fullName}"
          - "${sysvar.rootPipeline.executionId}"
          - "abc"
          - "table"
          - "0"
          - "0"
          - ""
          - "${new Date().toISOString()}"
          - "Y"
          - "${sysvar.thisComponent.startedAt}"
          - ""
          - "0"
          - "${sysvar.rootPipeline.executionId}"
          - "Successful"
          - "Jobs completed state"
          - "Jobs"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Logs for Completed Jobs:
      type: "run-shared-pipeline"
      skipped: false
      parameters:
        componentName: "Logs for Completed Jobs"
        pipelineName: "EDW_LAB#load_log_insert_orc"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
        - variable: "gv_load_log"
          status: "grid"
          gridValues:
            fromGrid:
              variable: "gv_load_log1"
              columns:
              - "gv_load_id"
              - "gv_job_name"
              - "gv_job_parent"
              - "gv_table_name"
              - "gv_table_type"
              - "gv_inserted_rows"
              - "gv_updated_rows"
              - "gv_subject_area"
              - "gv_process_date"
              - "gv_success_flag"
              - "gv_start_time"
              - "gv_end_time"
              - "gv_row_count"
              - "gv_run_history_id"
              - "gv_status"
              - "gv_message"
              - "gv_comment"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    Jv_process_date:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    Jv_load_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1"
    v_current_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "JOB_1"
    jv_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_seq:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "1"
    jv_success_flag:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Y"
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "STAGE_REGION_TABLE"
    jv_end_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_run_history_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_updated_rows:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    Jv_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "JOB_1"
    jv_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_job_parent:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_status:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Success"
    jv_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_detailed_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    Jv_job_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1"
    gv_load_log1:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "TEXT"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "NUMBER"
          gv_subject_area:
            columnType: "TEXT"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "TEXT"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_run_history_id:
            columnType: "TEXT"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
          gv_comment:
            columnType: "TEXT"
      defaultValue:
      - - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
        - "-1"
    gv_error_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "NUMBER"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_error_rows:
            columnType: "TEXT"
          gv_subject_area:
            columnType: "TEXT"
          gv_run_date:
            columnType: "TEXT"
          gv_run_time:
            columnType: "TEXT"
          gv_run_history_id:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
      defaultValue: []
    gv_ready_jobs:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          job_seq:
            columnType: "NUMBER"
          job_name:
            columnType: "TEXT"
          table_name:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -360
        "y": 0
      tempMetlId: 1
    Run Orchestration:
      position:
        x: 100
        "y": 0
      tempMetlId: 2
    Mark Job Running:
      position:
        x: -20
        "y": 0
      tempMetlId: 8
    Mark Job Failed:
      position:
        x: 220
        "y": 150
      tempMetlId: 10
    'Mark Job Completed ':
      position:
        x: 250
        "y": -50
      tempMetlId: 11
    Logs append 2:
      position:
        x: -280
        "y": 0
      tempMetlId: 20
    Logs for Running:
      position:
        x: -150
        "y": 0
      tempMetlId: 21
    Append To Grid 2 2 2:
      position:
        x: 350
        "y": 150
      tempMetlId: 24
    Run Shared Pipeline 2 2:
      position:
        x: 480
        "y": 150
      tempMetlId: 25
    Logs append 3:
      position:
        x: 390
        "y": -50
      tempMetlId: 26
    Logs for Completed Jobs:
      position:
        x: 520
        "y": -50
      tempMetlId: 27
  notes:
    "1":
      position:
        x: 160
        "y": -100
      size:
        height: 138
        width: 510
      theme: "green"
      content: "Success Path"
    "2":
      position:
        x: 160
        "y": 80
      size:
        height: 168
        width: 510
      theme: "red"
      content: "Failure Path"
