type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      parameters:
        componentName: "Start"
  variables:
    Child_var:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "200"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
