type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Orchestration"
      parameters:
        componentName: "Start"
    Run Orchestration:
      type: "run-orchestration"
      parameters:
        componentName: "Run Orchestration"
        orchestrationJob: "Trail Folder/child_O.orch.yaml"
        setScalarVariables:
        - - "Child_var"
          - "${Parent_var}"
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    Parent_var:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "100"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Run Orchestration:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
