type: "orchestration"
version: "1.0"
pipeline:
  components:
    Get source system data:
      type: "query-to-grid"
      transitions:
        success:
        - "SQL Script"
      skipped: false
      parameters:
        componentName: "Get source system data"
        mode: "Advanced"
        query: "/* Note: this query will be run as a subquery for the purposes of\
          \ sampling the data.\n   As such it will be restricted by any subquery limitations\
          \ specified by the current platform. */\n   \n   select ss.Source_system_code,so.*\n\
          \   from edw_lab.public.Source_Objects so \n   left join edw_lab.public.Source_system\
          \ ss \n   on ss.Source_system_id = so.Source_system_id\n   where so.active_flag\
          \ = 1 and ss.active_flag = 1 AND SOURCE_OBJECT_ID IN(1,2)\n   "
        gridVariable: "gv_source_system"
        gridVariableMapping:
        - - "SOURCE_SYSTEM_CODE"
          - "source_system_code"
        - - "SOURCE_OBJECT_ID"
          - "Source_Object_id"
        - - "SOURCE_SYSTEM_ID"
          - "Source_System_id"
        - - "OBJECT_TYPE"
          - "Object_type"
        - - "OBJECT_NAME"
          - "Object_name"
        - - "REFRESH_FREQUENCY"
          - "Refresh_frequency"
        - - "REFRESH_TYPE"
          - "Refresh_type"
        - - "SOURCE_CUSTOM_QUERY"
          - "Source_custom_query"
        - - "ACTIVE_FLAG"
          - "Active_flag"
        - - "TARGET_TABLE"
          - "Target_table"
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Get source system data"
      skipped: false
      parameters:
        componentName: "Start 0"
    End Failure 0:
      type: "end-failure"
      skipped: false
      parameters:
        componentName: "End Failure 0"
    Main_Source_Selector 0:
      type: "run-orchestration"
      skipped: false
      parameters:
        componentName: "Main_Source_Selector 0"
        orchestrationJob: "Ingestion Framework/${jv_source_system_code}_Load"
        setScalarVariables:
        - - "jv_source_system_code"
          - "${jv_source_system_code}"
        - - "jv_source_system_id"
          - "${jv_source_system_id}"
        - - "jv_active_flag"
          - "${jv_active_flag}"
        - - "jv_object_name"
          - "${jv_object_name}"
        - - "jv_object_type"
          - "${jv_object_type}"
        - - "jv_refresh_frequency"
          - "${jv_refresh_frequency}"
        - - "jv_refresh_type"
          - "${jv_refresh_type}"
        - - "jv_source_custom_query"
          - "${jv_source_custom_query}"
        - - "jv_target_table"
          - "${jv_target_table}"
        - - "jv_source_object_id"
          - "${jv_source_object_id}"
        setGridVariables:
      postProcessing:
        updateScalarVariables:
        - - "jv_message"
          - "${sysvar.thisComponent.message}"
    End Success 0:
      type: "end-success"
      skipped: false
      parameters:
        componentName: "End Success 0"
    Grid Iterator 0:
      type: "grid-iterator"
      transitions:
        success:
        - "SQL Script 2"
        failure:
        - "Python Pushdown"
      iterationTarget: "Main_Source_Selector 0"
      skipped: false
      parameters:
        componentName: "Grid Iterator 0"
        gridVariable: "gv_source_system"
        gridIteratorVariableMapping:
        - - "source_system_code"
          - "jv_source_system_code"
        - - "Source_System_id"
          - "jv_source_system_id"
        - - "Source_Object_id"
          - "jv_source_object_id"
        - - "Object_type"
          - "jv_object_type"
        - - "Object_name"
          - "jv_object_name"
        - - "Refresh_frequency"
          - "jv_refresh_frequency"
        - - "Refresh_type"
          - "jv_refresh_type"
        - - "Source_custom_query"
          - "jv_source_custom_query"
        - - "Active_flag"
          - "jv_active_flag"
        - - "Target_table"
          - "jv_target_table"
        concurrency: "Concurrent"
      postProcessing:
        updateScalarVariables:
        - - "jv_status"
          - "${sysvar.thisComponent.status}"
        - - "jv_end_time"
          - "${sysvar.thisComponent.mainTaskFinishedAt}"
        - - "jv_start_time"
          - "${sysvar.thisComponent.startedAt}"
    Run Shared Pipeline:
      type: "run-shared-pipeline"
      transitions:
        success:
        - "End Failure 0"
      parameters:
        componentName: "Run Shared Pipeline"
        pipelineName: "EDW_LAB#Error_log_o"
        version: "[Latest]"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script:
      type: "sql-executor"
      transitions:
        success:
        - "Grid Iterator 0"
      parameters:
        componentName: "SQL Script"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "insert into  edw_lab.framework.Source_Object_Ingestion_log\r\n\
          (Batch_run_id,Source_system_id,Source_object_id,Status,Run_start_time) \r\
          \nvalues ('${task_id}','${jv_source_system_id}','${jv_source_object_id}','STARTED',current_timestamp);"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script 2:
      type: "sql-executor"
      transitions:
        success:
        - "End Success 0"
      parameters:
        componentName: "SQL Script 2"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "update edw_lab.framework.Source_Object_Ingestion_log\r\nset Run_end_time\
          \ = current_timestamp where batch_run_id = '${task_id}'"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Python Pushdown:
      type: "python-pushdown"
      transitions:
        success:
        - "Run Shared Pipeline"
      parameters:
        componentName: "Python Pushdown"
        warehouse: "[Environment Default]"
        externalAccessIntegrations:
        pythonVersion: "3.10"
        packagesGrid:
        scriptLocation: "Component"
        pythonScript: "###\n# Variables are directly accessible: \n#   print (myvar)\n\
          # Updating a variable:\n#   context.updateVariable('myvar', 'new-value')\n\
          # Grid Variables are accessible via the context:\n#   print (context.getGridVariable('mygridvar'))\n\
          # Updating a grid variable:\n#   context.updateGridVariable('mygridvar',\
          \ [['list','of'],['lists','!']])\n# A database cursor can be accessed from\
          \ the context (Jython only):\n#   cursor = context.cursor()\n#   cursor.execute('select\
          \ count(*) from mytable')\n#   rowcount = cursor.fetchone()[0]\n###\n\n\
          context.updateVariable('jv_error_message' , jv_message)\nprint(jv_error_message)"
        scriptTimeout: "360"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_object_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_last_run_dt:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2022-02-01"
    jv_refresh_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_comment:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_error_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_refresh_frequency:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "1"
    jv_table_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "DEFAULT"
    jv_end_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1970-01-01"
    jv_run_history_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_source_custom_query:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "NA"
    jv_source_object_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "9"
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "None"
    jv_status:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "None"
    jv_job_parent:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "None"
    jv_object_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "Ingestion/test.csv"
    jv_target_table:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "COL_DATA"
    jv_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1970-01-01"
    jv_error_number:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_active_flag:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "Y"
    jv_inserted_rows:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_subject_area:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "Fact Sales"
    jv_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_success_flag:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1"
    jv_process_date:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2021-01-01"
    jv_updated_rows:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    jv_load_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "-1"
    jv_source_system_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "1"
    jv_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "None"
    jv_curr_run_dt:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "2022-06-01"
    jv_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "DEFAULT"
    jv_source_system_code:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "Postgres"
    gv_error_log:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_load_id:
            columnType: "TEXT"
          gv_job_name:
            columnType: "TEXT"
          gv_job_parent:
            columnType: "TEXT"
          gv_table_name:
            columnType: "TEXT"
          gv_table_type:
            columnType: "TEXT"
          gv_inserted_rows:
            columnType: "NUMBER"
          gv_updated_rows:
            columnType: "TEXT"
          gv_subject_area:
            columnType: "TEXT"
          gv_process_date:
            columnType: "TEXT"
          gv_success_flag:
            columnType: "NUMBER"
          gv_start_time:
            columnType: "TEXT"
          gv_end_time:
            columnType: "TEXT"
          gv_row_count:
            columnType: "NUMBER"
          gv_run_history_id:
            columnType: "NUMBER"
          gv_status:
            columnType: "TEXT"
          gv_message:
            columnType: "TEXT"
          gv_error_rows:
            columnType: "NUMBER"
          gv_error_number:
            columnType: "NUMBER"
          gv_error_message:
            columnType: "TEXT"
      defaultValue: []
    gv_source_system:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          source_system_code:
            columnType: "TEXT"
          Source_Object_id:
            columnType: "TEXT"
          Source_System_id:
            columnType: "TEXT"
          Object_type:
            columnType: "TEXT"
          Object_name:
            columnType: "TEXT"
          Refresh_frequency:
            columnType: "TEXT"
          Refresh_type:
            columnType: "TEXT"
          Source_custom_query:
            columnType: "TEXT"
          Active_flag:
            columnType: "TEXT"
          Target_table:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Get source system data:
      position:
        x: -1870
        "y": 0
      tempMetlId: 912674
    Start 0:
      position:
        x: -2032
        "y": 0
      tempMetlId: 912675
    End Failure 0:
      position:
        x: -1210
        "y": 150
      tempMetlId: 912692
    Main_Source_Selector 0:
      position:
        x: -1520
        "y": -20
      tempMetlId: 912697
    End Success 0:
      position:
        x: -1216
        "y": 0
      tempMetlId: 912698
    Grid Iterator 0:
      position:
        x: -1520
        "y": -20
      tempMetlId: 912700
    Run Shared Pipeline:
      position:
        x: -1370
        "y": 150
      tempMetlId: 913435
    SQL Script:
      position:
        x: -1710
        "y": 0
      tempMetlId: 913436
    SQL Script 2:
      position:
        x: -1360
        "y": 0
      tempMetlId: 913437
    Python Pushdown:
      position:
        x: -1500
        "y": 150
      tempMetlId: 913438
  notes:
    "912672":
      position:
        x: -1937
        "y": -43
      size:
        height: 119
        width: 782
      theme: "green"
      content: "Success Path"
    "912673":
      position:
        x: -1600
        "y": 100
      size:
        height: 127
        width: 472
      theme: "red"
      content: "Failure Path"
