type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/JOB1_trans.tran.yaml"
        setScalarVariables:
        - - "Jv_job_id"
          - "${ev_job_id}"
        - - "Jv_Job_name"
          - "${ev_job_name}"
        - - "jv_dependenies_on_job_id"
          - "${ev_dependency_on_job_id}"
        - - "jv_run_type"
          - "${jv_run_type}"
        - - "jv_execution_order"
          - "${ev_execution_order}"
        - - "jv_job_group_id"
          - "${ev_job_group_id}"
        - - "jv_active_flag"
          - "${ev_active_flag}"
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_active_flag:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_execution_code:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_run_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    Jv_group_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_dependenies_on_job_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    Jv_job_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start:
      position:
        x: -90
        "y": 20
      tempMetlId: 1
    Run Transformation:
      position:
        x: 70
        "y": 20
      tempMetlId: 2
