type: "transformation"
version: "1.0"
pipeline:
  components:
    REGION:
      type: "table-input"
      parameters:
        componentName: "REGION"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF100"
        targetTable: "REGION"
        columnNames:
        - "R_REGIONKEY"
        - "R_NAME"
        - "R_COMMENT"
        timeOffset:
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "REGION"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "${v_current_table_name}"
        orderBy:
      postProcessing:
        updateOutputMessage: "Row count: ${v_row_count}\r\n\r\nTable name:${x_table_name}"
        updateScalarVariables:
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    x_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "STAGE_REGION_TABLE"
design:
  components:
    REGION:
      position:
        x: -300
        "y": 10
      tempMetlId: 1
    Rewrite Table:
      position:
        x: -140
        "y": 10
      tempMetlId: 2
