type: "transformation"
version: "1.0"
pipeline:
  components:
    REGION:
      type: "table-input"
      parameters:
        componentName: "REGION"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF100"
        targetTable: "REGION"
        columnNames:
        - "R_REGIONKEY"
        - "R_NAME"
        - "R_COMMENT"
        timeOffset:
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "REGION"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STAGE_REGION_TABLE"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    REGION:
      position:
        x: -300
        "y": 10
      tempMetlId: 1
    Rewrite Table:
      position:
        x: -140
        "y": 10
      tempMetlId: 2
