type: "transformation"
version: "1.0"
pipeline:
  components:
    PARTSUPP:
      type: "table-input"
      parameters:
        componentName: "PARTSUPP"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF10"
        targetTable: "PARTSUPP"
        columnNames:
        - "PS_PARTKEY"
        - "PS_SUPPKEY"
        - "PS_AVAILQTY"
        - "PS_SUPPLYCOST"
        - "PS_COMMENT"
        timeOffset:
    STAGE PARTSUPP:
      type: "table-output"
      sources:
      - "PARTSUPP"
      parameters:
        componentName: "STAGE PARTSUPP"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STAGE_PARTSUPP"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "C_CUSTKEY"
          - "C_CUSTKEY"
        - - "C_NAME"
          - "C_NAME"
        - - "C_ADDRESS"
          - "C_ADDRESS"
        - - "C_NATIONKEY"
          - "C_NATIONKEY"
        - - "C_PHONE"
          - "C_PHONE"
        - - "C_ACCTBAL"
          - "C_ACCTBAL"
        - - "C_MKTSEGMENT"
          - "C_MKTSEGMENT"
        - - "C_COMMENT"
          - "C_COMMENT"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    PARTSUPP:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    STAGE PARTSUPP:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
