type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - "JOB 6 End Success"
        failure:
        - "JOB 6 End Failure"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/Tjob6.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 6 End Success:
      type: "end-success"
      parameters:
        componentName: "JOB 6 End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 6 End Failure:
      type: "end-failure"
      parameters:
        componentName: "JOB 6 End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -240
        "y": -70
      tempMetlId: 1
    Run Transformation:
      position:
        x: -80
        "y": -70
      tempMetlId: 2
    JOB 6 End Success:
      position:
        x: 0
        "y": -170
      tempMetlId: 3
    JOB 6 End Failure:
      position:
        x: 20
        "y": 0
      tempMetlId: 4
