type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - "JOB 5 End Success"
        failure:
        - "JOB 5 End Failure"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/Tjob5.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 5 End Failure:
      type: "end-failure"
      parameters:
        componentName: "JOB 5 End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 5 End Success:
      type: "end-success"
      parameters:
        componentName: "JOB 5 End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "JOB_1"
    v_current_job_seq:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "1"
design:
  components:
    Start:
      position:
        x: -70
        "y": 0
      tempMetlId: 1
    Run Transformation:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
    JOB 5 End Failure:
      position:
        x: 460
        "y": 50
      tempMetlId: 3
    JOB 5 End Success:
      position:
        x: 440
        "y": -70
      tempMetlId: 4
