type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run JOB2"
      parameters:
        componentName: "Start"
    Run JOB2:
      type: "run-transformation"
      parameters:
        componentName: "Run JOB2"
        transformationJob: "EDW STAGE/Trans_JOB2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_current_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_seq:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Run JOB2:
      position:
        x: 110
        "y": -10
      tempMetlId: 2
