type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - "Print Variables"
        failure:
        - "JOB 1 End Failure"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/job1_trans.tran.yaml"
        setScalarVariables:
        - - "v_current_table_name"
          - "${v_current_table_name}"
        setGridVariables:
      postProcessing:
        updateOutputMessage: "Row Count: ${v_row_count}\r\n\r\nTable name: ${x_table_name}"
        updateScalarVariables:
        - - "v_row_count"
          - "${sysvar.childPipeline.vars.v_row_count}"
        - - "x_table_name"
          - "${sysvar.childPipeline.vars.x_table_name}"
        - - "x_start_time"
          - "${sysvar.thisComponent.startedAt}"
        - - "x_end_time"
          - "${sysvar.thisComponent.mainTaskFinishedAt}"
        - - "v_error_message"
          - "${sysvar.childPipeline.vars.v_error_message}"
    JOB 1 End Failure:
      type: "end-failure"
      parameters:
        componentName: "JOB 1 End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 1 End Success:
      type: "end-success"
      parameters:
        componentName: "JOB 1 End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables:
      type: "print-variables"
      transitions:
        success:
        - "JOB 1 End Success"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "v_row_count"
        - - "v_current_table_name"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage: "Row count:${v_rowcount}\r\nTable Name: ${x_table_name}\r\
          \nstart_time:${x_start_time}\r\nEnd time:${x_end_time}"
        updateScalarVariables:
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    x_end_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "JOB_1"
    v_current_job_seq:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "1"
    x_start_time:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "abc"
design:
  components:
    Start:
      position:
        x: -70
        "y": 0
      tempMetlId: 1
    Run Transformation:
      position:
        x: 80
        "y": 0
      tempMetlId: 2
    JOB 1 End Failure:
      position:
        x: 360
        "y": 80
      tempMetlId: 3
    JOB 1 End Success:
      position:
        x: 310
        "y": -100
      tempMetlId: 4
    Print Variables:
      position:
        x: 190
        "y": -90
      tempMetlId: 5
