type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run JOB2"
      parameters:
        componentName: "Start"
    Run JOB2:
      type: "run-transformation"
      transitions:
        success:
        - "JOB 2 End Success"
        failure:
        - "JOB 2 End Failure"
      parameters:
        componentName: "Run JOB2"
        transformationJob: "EDW STAGE/Trans_JOB2.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 2 End Success:
      type: "end-success"
      parameters:
        componentName: "JOB 2 End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 2 End Failure:
      type: "end-failure"
      parameters:
        componentName: "JOB 2 End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_current_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_seq:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Run JOB2:
      position:
        x: 110
        "y": -10
      tempMetlId: 2
    JOB 2 End Success:
      position:
        x: 220
        "y": -80
      tempMetlId: 3
    JOB 2 End Failure:
      position:
        x: 210
        "y": 50
      tempMetlId: 4
