type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation :JOB 3"
      parameters:
        componentName: "Start"
    Run Transformation :JOB 3:
      type: "run-transformation"
      transitions:
        success:
        - "Print Variables"
        failure:
        - "Print Variables 2"
      parameters:
        componentName: "Run Transformation :JOB 3"
        transformationJob: "EDW STAGE/Trans_JOB3.tran.yaml"
        setScalarVariables:
        - - "v_current_table_name"
          - "${v_current_table_name}"
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.childPipeline.vars.v_error_message}"
        - - "v_row_count"
          - "${sysvar.childPipeline.vars.v_row_count}"
    JOB 3 End Failure:
      type: "end-failure"
      parameters:
        componentName: "JOB 3 End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 3 End Success:
      type: "end-success"
      parameters:
        componentName: "JOB 3 End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables:
      type: "print-variables"
      transitions:
        success:
        - "JOB 3 End Success"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "v_row_count"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage: "JOB :  ${v_current_job_name} success\r\n\r\nTABLE NAME:\
          \ ${v_current_table_name}\r\n\r\nRow_count:  ${v_row_count} "
        updateScalarVariables:
    Print Variables 2:
      type: "print-variables"
      transitions:
        success:
        - "JOB 3 End Failure"
      parameters:
        componentName: "Print Variables 2"
        variablesToPrint:
        - - "v_row_count"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage: "JOB :  ${v_current_job_name} success\r\n\r\nTABLE NAME:\
          \ ${v_current_table_name}\r\n\r\nRow_count:  ${v_row_count} "
        updateScalarVariables:
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_job_seq:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "3"
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    Start:
      position:
        x: -70
        "y": 0
      tempMetlId: 1
    Run Transformation :JOB 3:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
    JOB 3 End Failure:
      position:
        x: 460
        "y": 50
      tempMetlId: 3
    JOB 3 End Success:
      position:
        x: 440
        "y": -70
      tempMetlId: 4
    Print Variables:
      position:
        x: 290
        "y": -40
      tempMetlId: 5
    Print Variables 2:
      position:
        x: 330
        "y": 60
      tempMetlId: 6
