type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/Tjob6.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -240
        "y": -70
      tempMetlId: 1
    Run Transformation:
      position:
        x: -80
        "y": -70
      tempMetlId: 2
