type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - " JOB 5 End Success"
        failure:
        - "JOB 5 End Failure"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/Tjob5.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    ' JOB 5 End Success':
      type: "end-success"
      parameters:
        componentName: " JOB 5 End Success"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    JOB 5 End Failure:
      type: "end-failure"
      parameters:
        componentName: "JOB 5 End Failure"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -650
        "y": -10
      tempMetlId: 1
    Run Transformation:
      position:
        x: -520
        "y": -10
      tempMetlId: 2
    ' JOB 5 End Success':
      position:
        x: -400
        "y": -10
      tempMetlId: 3
    JOB 5 End Failure:
      position:
        x: -410
        "y": 70
      tempMetlId: 4
