type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "EDW STAGE/JOB1_tran1.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage: "CUSTOMER TABLE EXECUTED............."
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -200
        "y": 10
      tempMetlId: 1
    Run Transformation:
      position:
        x: -40
        "y": 10
      tempMetlId: 2
