type: "transformation"
version: "1.0"
pipeline:
  components:
    SQL:
      type: "sql"
      parameters:
        componentName: "SQL"
        query: "select top 100000000 * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "SQL"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "INTERNAL_TRAINING"
        schema: "DBT_MKHAMBADKAR"
        targetTable: "TransfromationJob16"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    SQL:
      position:
        x: -70
        "y": -50
      tempMetlId: 1
    Rewrite Table:
      position:
        x: 120
        "y": -50
      tempMetlId: 2
