type: "transformation"
version: "1.0"
pipeline:
  components:
    SQL:
      type: "sql"
      parameters:
        componentName: "SQL"
        query: "select  * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.PARTSUPP"
    PART2 :JOB_7:
      type: "rewrite-table"
      sources:
      - "SQL"
      parameters:
        componentName: "PART2 :JOB_7"
        warehouse: "[Environment Default]"
        database: "SCD_PRACTICE_DB"
        schema: "PUBLIC"
        targetTable: "PART2"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowsInserted}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "PART2"
design:
  components:
    SQL:
      position:
        x: -210
        "y": -60
      tempMetlId: 1
    PART2 :JOB_7:
      position:
        x: -50
        "y": -60
      tempMetlId: 2
