type: "transformation"
version: "1.0"
pipeline:
  components:
    NATION :JOB 6:
      type: "rewrite-table"
      sources:
      - "NATION"
      parameters:
        componentName: "NATION :JOB 6"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "${v_current_table_name}"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
    NATION:
      type: "table-input"
      parameters:
        componentName: "NATION"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF100"
        targetTable: "NATION"
        columnNames:
        - "N_NATIONKEY"
        - "N_NAME"
        - "N_REGIONKEY"
        - "N_COMMENT"
        timeOffset:
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "abcc6"
design:
  components:
    NATION :JOB 6:
      position:
        x: -240
        "y": -100
      tempMetlId: 2
    NATION:
      position:
        x: -450
        "y": -100
      tempMetlId: 3
