type: "transformation"
version: "1.0"
pipeline:
  components:
    SQL:
      type: "sql"
      parameters:
        componentName: "SQL"
        query: "select  Top 100000 * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM--"
    JOB 5 Line_item2:
      type: "rewrite-table"
      sources:
      - "SQL"
      parameters:
        componentName: "JOB 5 Line_item2"
        warehouse: "[Environment Default]"
        database: "SCD_PRACTICE_DB"
        schema: "PUBLIC"
        targetTable: "Line_item2"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowsInserted}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    SQL:
      position:
        x: -290
        "y": -70
      tempMetlId: 1
    JOB 5 Line_item2:
      position:
        x: -130
        "y": -70
      tempMetlId: 2
