type: "transformation"
version: "1.0"
pipeline:
  components:
    NATION :JOB 6:
      type: "rewrite-table"
      sources:
      - "NATION"
      parameters:
        componentName: "NATION :JOB 6"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "NATION"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    NATION:
      type: "table-input"
      parameters:
        componentName: "NATION"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF100"
        targetTable: "NATION"
        columnNames:
        - "N_NATIONKEY"
        - "N_NAME"
        - "N_REGIONKEY"
        - "N_COMMENT"
        timeOffset:
design:
  components:
    NATION :JOB 6:
      position:
        x: -240
        "y": -100
      tempMetlId: 2
    NATION:
      position:
        x: -450
        "y": -100
      tempMetlId: 3
