type: "transformation"
version: "1.0"
pipeline:
  components:
    ORDERS:
      type: "table-input"
      parameters:
        componentName: "ORDERS"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF1"
        targetTable: "ORDERS"
        columnNames:
        - "O_ORDERKEY"
        - "O_CUSTKEY"
        - "O_ORDERSTATUS"
        - "O_TOTALPRICE"
        - "O_ORDERDATE"
        - "O_ORDERPRIORITY"
        - "O_CLERK"
        - "O_SHIPPRIORITY"
        - "O_COMMENT"
        timeOffset:
    Orders:
      type: "rewrite-table"
      sources:
      - "ORDERS"
      parameters:
        componentName: "Orders"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "${v_current_table_name}"
        orderBy:
      postProcessing:
        updateOutputMessage: ""
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "0"
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "STAGE_REGION_TABLE"
design:
  components:
    ORDERS:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Orders:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
