type: "transformation"
version: "1.0"
pipeline:
  components:
    ORDERS:
      type: "table-input"
      parameters:
        componentName: "ORDERS"
        database: "TEST_DB_STREAMLIT"
        schema: "TPCH_SF1"
        targetTable: "ORDERS"
        columnNames:
        - "O_ORDERKEY"
        - "O_CUSTKEY"
        - "O_ORDERSTATUS"
        - "O_TOTALPRICE"
        - "O_ORDERDATE"
        - "O_ORDERPRIORITY"
        - "O_CLERK"
        - "O_SHIPPRIORITY"
        - "O_COMMENT"
        timeOffset:
    Rewrite Table:
      type: "rewrite-table"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable:
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_dependenies_on_job_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    ORDERS:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Rewrite Table:
      position:
        x: -40
        "y": -80
      tempMetlId: 2
