type: "transformation"
version: "1.0"
pipeline:
  components:
    ORDERS:
      type: "table-input"
      parameters:
        componentName: "ORDERS"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF1"
        targetTable: "ORDERS"
        columnNames:
        - "O_ORDERKEY"
        - "O_CUSTKEY"
        - "O_ORDERSTATUS"
        - "O_TOTALPRICE"
        - "O_ORDERDATE"
        - "O_ORDERPRIORITY"
        - "O_CLERK"
        - "O_SHIPPRIORITY"
        - "O_COMMENT"
        timeOffset:
    'JOB 2 : ORDER TABLE':
      type: "rewrite-table"
      sources:
      - "ORDERS"
      parameters:
        componentName: "JOB 2 : ORDER TABLE"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STAGE_ORDERS_TABLE"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowsInserted}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
design:
  components:
    ORDERS:
      position:
        x: -180
        "y": -80
      tempMetlId: 1
    'JOB 2 : ORDER TABLE':
      position:
        x: -40
        "y": -80
      tempMetlId: 2
