type: "transformation"
version: "1.0"
pipeline:
  components:
    PARTSUPP:
      type: "table-input"
      parameters:
        componentName: "PARTSUPP"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF100"
        targetTable: "PARTSUPP"
        columnNames:
        - "PS_PARTKEY"
        - "PS_SUPPKEY"
        - "PS_AVAILQTY"
        - "PS_SUPPLYCOST"
        - "PS_COMMENT"
        timeOffset:
    'PARTSUPP TARGET ':
      type: "rewrite-table"
      sources:
      - "PARTSUPP"
      parameters:
        componentName: "PARTSUPP TARGET "
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STAGE_PARTSUPP_TABLE"
        orderBy:
      postProcessing:
        updateOutputMessage: "JOB 4: PARTSUPP EXECUTED"
        updateScalarVariables:
design:
  components:
    PARTSUPP:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    'PARTSUPP TARGET ':
      position:
        x: 160
        "y": 0
      tempMetlId: 2
