type: "transformation"
version: "1.0"
pipeline:
  components:
    Supplier:
      type: "table-input"
      parameters:
        componentName: "Supplier"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF10"
        targetTable: "SUPPLIER"
        columnNames:
        - "S_SUPPKEY"
        - "S_NAME"
        - "S_ADDRESS"
        - "S_NATIONKEY"
        - "S_PHONE"
        - "S_ACCTBAL"
        - "S_COMMENT"
        timeOffset:
    SUPPLIER 5:
      type: "rewrite-table"
      sources:
      - "Supplier"
      parameters:
        componentName: "SUPPLIER 5"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "${v_current_table_name}"
        orderBy:
      postProcessing:
        updateOutputMessage: ""
        updateScalarVariables:
        - - "v_error_message"
          - "${sysvar.thisComponent.message}"
        - - "v_row_count"
          - "${sysvar.thisComponent.rowCount}"
  variables:
    v_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    v_current_table_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "abc5"
design:
  components:
    Supplier:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    SUPPLIER 5:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
