type: "transformation"
version: "1.0"
pipeline:
  components:
    LINE ITEM:
      type: "table-input"
      parameters:
        componentName: "LINE ITEM"
        database: "SNOWFLAKE_SAMPLE_DATA"
        schema: "TPCH_SF10"
        targetTable: "LINEITEM"
        columnNames:
        - "L_ORDERKEY"
        - "L_PARTKEY"
        - "L_SUPPKEY"
        - "L_LINENUMBER"
        - "L_QUANTITY"
        - "L_EXTENDEDPRICE"
        - "L_DISCOUNT"
        - "L_TAX"
        - "L_RETURNFLAG"
        - "L_LINESTATUS"
        - "L_SHIPDATE"
        - "L_COMMITDATE"
        - "L_RECEIPTDATE"
        - "L_SHIPINSTRUCT"
        - "L_SHIPMODE"
        - "L_COMMENT"
        timeOffset:
    STAGE LINEITEM:
      type: "table-output"
      sources:
      - "LINE ITEM"
      parameters:
        componentName: "STAGE LINEITEM"
        warehouse: "[Environment Default]"
        database: "EDW_LAB"
        schema: "PUBLIC"
        targetTable: "STAGE_LINEITEM"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "L_ORDERKEY"
          - "L_ORDERKEY"
        - - "L_PARTKEY"
          - "L_PARTKEY"
        - - "L_SUPPKEY"
          - "L_SUPPKEY"
        - - "L_LINENUMBER"
          - "L_LINENUMBER"
        - - "L_QUANTITY"
          - "L_QUANTITY"
        - - "L_EXTENDEDPRICE"
          - "L_EXTENDEDPRICE"
        - - "L_DISCOUNT"
          - "L_DISCOUNT"
        - - "L_TAX"
          - "L_TAX"
        - - "L_RETURNFLAG"
          - "L_RETURNFLAG"
        - - "L_LINESTATUS"
          - "L_LINESTATUS"
        - - "L_SHIPDATE"
          - "L_SHIPDATE"
        - - "L_COMMITDATE"
          - "L_COMMITDATE"
        - - "L_RECEIPTDATE"
          - "L_RECEIPTDATE"
        - - "L_SHIPINSTRUCT"
          - "L_SHIPINSTRUCT"
        - - "L_SHIPMODE"
          - "L_SHIPMODE"
        - - "L_COMMENT"
          - "L_COMMENT"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    LINE ITEM:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    STAGE LINEITEM:
      position:
        x: 160
        "y": 0
      tempMetlId: 2
