type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Log Running"
      parameters:
        componentName: "Start"
    Log Running:
      type: "sql-executor"
      transitions:
        success:
        - "TARGET_TABLE EXISTS"
      parameters:
        componentName: "Log Running"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "insert into edw_lab.public.JOB_RUN_AUDIT(BATCH_ID,run_id,JOB_NAME,Source_system_id,SOURCE_OBJECT_ID,object_name,STATUS,START_TIME)\r\
          \nvalues('${sysvar.rootPipeline.executionId}','${sysvar.thisPipeline.executionId}','${sysvar.thisPipeline.fullName}','${jv_source_system_id}','${jv_source_object_id}','${jv_object_name}','RUNNING',current_timestamp)\
          \  "
      postProcessing:
        updateOutputMessage: "Marked as Running Jobs : '${jv_source_object_name}'\
          \ AND '${jv_src_db}'"
        updateScalarVariables:
    TARGET_TABLE EXISTS:
      type: "database-query"
      transitions:
        success:
        - "Checking Target Tables exists or not "
      parameters:
        componentName: "TARGET_TABLE EXISTS"
        basicAdvancedMode: "Advanced"
        databaseType: "Snowflake"
        connectionUrl: "jdbc:snowflake://https://kha80474.snowflakecomputing.com"
        username: "mohanishk@cloudeqs.com"
        password: "sf_m_password"
        connectionOptions:
        sqlQuery: "SELECT TABLE_NAME\r\nFROM ${jv_tar_db}.INFORMATION_SCHEMA.TABLES\r\
          \nWHERE TABLE_CATALOG = '${jv_tar_db}'\r\n  AND TABLE_SCHEMA = '${jv_tar_schema}'\r\
          \n  AND TABLE_NAME = '${jv_target_table}'"
        fetchSize:
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "${jv_tar_db}"
        schema: "${jv_tar_schema}"
        targetTable: "TABLE_COUNT"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        sshTunnel:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
        - - "jv_tables_exists"
          - "${sysvar.thisComponent.rowCount}"
    Print Variables:
      type: "print-variables"
      parameters:
        componentName: "Print Variables"
        variablesToPrint:
        - - "jv_tables_exists"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage: "Target table Exists : '${jv_target_table} : ${jv_tables_exists}"
        updateScalarVariables:
    'Checking Target Tables exists or not ':
      type: "if"
      transitions:
        "true":
        - "Print Variables"
        - "If"
        - "If 2"
        "false":
        - "Print Variables 2"
      parameters:
        componentName: "Checking Target Tables exists or not "
        mode: "Simple"
        condition:
        - - "jv_tables_exists"
          - "Is"
          - "Equal to"
          - "1"
        combineConditions: "And"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Print Variables 2:
      type: "print-variables"
      parameters:
        componentName: "Print Variables 2"
        variablesToPrint:
        - - "jv_tables_exists"
        prefixText:
        includeVariableName: "No"
      postProcessing:
        updateOutputMessage: "Target table  doesn't Exists : '${jv_target_table} :\
          \ ${jv_tables_exists}"
        updateScalarVariables:
    If:
      type: "if"
      transitions:
        "true":
        - "FULL"
      parameters:
        componentName: "If"
        mode: "Simple"
        condition:
        - - "jv_refresh_type"
          - "Is"
          - "Equal to"
          - "FULL"
        combineConditions: "And"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    If 2:
      type: "if"
      transitions:
        "true":
        - "Database Query 2"
      parameters:
        componentName: "If 2"
        mode: "Simple"
        condition:
        - - "jv_refresh_type"
          - "Is"
          - "Equal to"
          - "INCREMENTAL"
        combineConditions: "And"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    FULL:
      type: "database-query"
      parameters:
        componentName: "FULL"
        basicAdvancedMode: "Advanced"
        databaseType: "Snowflake"
        connectionUrl: "jdbc:snowflake://https://kha80474.snowflakecomputing.com"
        username: "mohanishk@cloudeqs.com"
        password:
        connectionOptions:
        sqlQuery: "select * from ${jv_src_db}.${jv_src_schema}.${jv_source_object_name}\
          \ limit 100"
        fetchSize:
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "${jv_tar_db}"
        schema: "${jv_tar_schema}"
        targetTable: "${jv_target_table}"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        sshTunnel:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Database Query 2:
      type: "database-query"
      parameters:
        componentName: "Database Query 2"
        basicAdvancedMode: "Advanced"
        databaseType: "Snowflake"
        connectionUrl: "jdbc:snowflake://https://kha80474.snowflakecomputing.com"
        username: "mohanishk@cloudeqs.com"
        password:
        connectionOptions:
        sqlQuery: "select * from ${jv_src_db}.${jv_src_schema}.${jv_source_object_name} "
        fetchSize:
        type: "Standard"
        primaryKeys:
        warehouse1: "[Environment Default]"
        database: "${jv_tar_db}"
        schema: "${jv_tar_schema}"
        targetTable: "${jv_target_table}"
        stage1: "[Custom]"
        stagePlatform: "Snowflake Managed"
        loadOptions:
        sshTunnel:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    jv_source_connection_url:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_last_updated:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_refresh_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_tar_schema:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "STAGE_SCHEMA"
    jv_tar_db:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "EDW_LAB"
    jv_column_data_type_exists:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_row_count:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_tables_exists:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_active_flage:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_role:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "RL_TRAINING"
    jv_column_datatype_exist:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_source_object_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "deafult"
    jv_src_db:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SOURCE_DB_TEST"
    jv_src_schema:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "SOURCE_SCHEMA"
    jv_source_object_type:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_source_object_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1"
    jv_source_system_id:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "1"
    jv_error_message:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    jv_target_table:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "STAGE_CUSTOMER"
    jv_source_system_code:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: ""
    gv_metadata_check:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          jv_status:
            columnType: "TEXT"
      defaultValue:
      - - "deafult status"
    gv_source_object_schema:
      metadata:
        type: "GRID"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
        columns:
          gv_field_name:
            columnType: "TEXT"
          gv_data_type:
            columnType: "TEXT"
      defaultValue: []
design:
  components:
    Start:
      position:
        x: -1210
        "y": -30
      tempMetlId: 1
    Log Running:
      position:
        x: -1070
        "y": -30
      tempMetlId: 2
    TARGET_TABLE EXISTS:
      position:
        x: -900
        "y": -30
      tempMetlId: 3
    Print Variables:
      position:
        x: -670
        "y": -150
      tempMetlId: 4
    'Checking Target Tables exists or not ':
      position:
        x: -750
        "y": -30
      tempMetlId: 5
    Print Variables 2:
      position:
        x: -670
        "y": 100
      tempMetlId: 6
    If:
      position:
        x: -610
        "y": -60
      tempMetlId: 7
    If 2:
      position:
        x: -610
        "y": 50
      tempMetlId: 8
    FULL:
      position:
        x: -440
        "y": -60
      tempMetlId: 9
    Database Query 2:
      position:
        x: -440
        "y": 50
      tempMetlId: 10
